package dev.cassis2310.falloutmc.datagen;

import dev.cassis2310.falloutmc.datagen.codecs.effects.EffectWithDuration;
import dev.cassis2310.falloutmc.datagen.codecs.items.ItemAttributes;
import dev.cassis2310.falloutmc.datagen.codecs.items.consumables.DrinkAttributes;
import dev.cassis2310.falloutmc.datagen.codecs.items.consumables.FoodAttributes;
import dev.cassis2310.falloutmc.datagen.codecs.items.consumables.SoupAttributes;
import dev.cassis2310.falloutmc.datagen.datamaps.FalloutMcDataMaps;
import dev.cassis2310.falloutmc.effects.FalloutMcEffects;
import dev.cassis2310.falloutmc.items.FalloutMcItems;
import net.minecraft.core.HolderLookup;
import net.minecraft.data.PackOutput;
import net.minecraft.world.item.Items;
import net.neoforged.neoforge.common.data.DataMapProvider;

import java.util.List;
import java.util.concurrent.CompletableFuture;

import static dev.cassis2310.falloutmc.utils.helpers.ItemHelpers.wrapItemAsHolder;

/**
 * This class is responsible for providing data maps.
 * It extends the {@link DataMapProvider} class to gather and register all the relevant data.
 */
public class FalloutMcDataMapProvider extends DataMapProvider
{

    /**
     * Creates a new instance of {@code FalloutMcDataMapProvider}.
     *
     * @param packOutput     the output location where data maps will be saved
     * @param lookupProvider a {@link CompletableFuture} that supplies the registries needed for data generation
     */
    protected FalloutMcDataMapProvider(PackOutput packOutput, CompletableFuture<HolderLookup.Provider> lookupProvider)
    {
        super(packOutput, lookupProvider);
    }

    /**
     * Gathers data map entries related to item weights.
     * This method populates the data map with item IDs and their corresponding weights.
     * The weights are used for various purposes, such as inventory management in the game.
     *
     * <h3>Usage Examples:</h3>
     * <p>
     * <h4>Example 1 (Furnace fuels):</h4>
     * <pre>{@code
     * this.builder(NeoForgeDataMaps.FURNACE_FUELS)
     *         .add(FalloutMcItems.NUCLEAR_SCRAP.getId(), new FurnaceFuel(1200), false);
     * }</pre>
     * </p>
     */
    @Override
    protected void gather()
    {
        addCustomItems();
        addVanillaItems();
    }

    /**
     * Adds custom items to the data map with their corresponding weights.
     * This method populates the item weight data map with custom items specific to the Fallout MC mod.
     * <p>
     * This method doesn't return any value and is called internally during the data gathering process.
     */
    private void addCustomItems()
    {
        // Custom items
        this.builder(FalloutMcDataMaps.DRINK_ATTRIBUTES)
                .add(FalloutMcItems.NUKA_COLA.getId(), new DrinkAttributes(20, 0, 0, List.of(new EffectWithDuration(FalloutMcEffects.EXAMPLE_EFFECT.value(), 0)), List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 12, 1, 0, false, false), false);
    }

    /**
     * Adds vanilla Minecraft items to the data map with their corresponding weights.
     * This method populates the item weight data map with standard building blocks available in Minecraft.
     * <p>
     * This method doesn't return any value and is called internally during the data gathering process.
     */
    private void addVanillaItems()
    {
        this.builder(FalloutMcDataMaps.ITEM_ATTRIBUTES)
            // Building Blocks
            .add(wrapItemAsHolder(Items.OAK_WOOD), new ItemAttributes(12.0, -1), false)
            .add(wrapItemAsHolder(Items.STRIPPED_OAK_WOOD), new ItemAttributes(11.0, -1), false)
            .add(wrapItemAsHolder(Items.OAK_PLANKS), new ItemAttributes(3.0, -1), false)
            .add(wrapItemAsHolder(Items.OAK_STAIRS), new ItemAttributes(5.0, -1), false)
            .add(wrapItemAsHolder(Items.OAK_SLAB), new ItemAttributes(1.5, -1), false)
            .add(wrapItemAsHolder(Items.OAK_FENCE), new ItemAttributes(4.0, -1), false)
            .add(wrapItemAsHolder(Items.OAK_FENCE_GATE), new ItemAttributes(5.0, -1), false)
            .add(wrapItemAsHolder(Items.OAK_DOOR), new ItemAttributes(8.0, -1), false)
            .add(wrapItemAsHolder(Items.OAK_TRAPDOOR), new ItemAttributes(4.0, -1), false)
            .add(wrapItemAsHolder(Items.OAK_PRESSURE_PLATE), new ItemAttributes(0.5, -1), false)
            .add(wrapItemAsHolder(Items.OAK_BUTTON), new ItemAttributes(0.1, -1), false)
            .add(wrapItemAsHolder(Items.OAK_SIGN), new ItemAttributes(1.0, -1), false)
            .add(wrapItemAsHolder(Items.SPRUCE_WOOD), new ItemAttributes(11.0, -1), false)
            .add(wrapItemAsHolder(Items.STRIPPED_SPRUCE_WOOD), new ItemAttributes(10.0, -1), false)
            .add(wrapItemAsHolder(Items.SPRUCE_PLANKS), new ItemAttributes(2.8, -1), false)
            .add(wrapItemAsHolder(Items.SPRUCE_STAIRS), new ItemAttributes(4.5, -1), false)
            .add(wrapItemAsHolder(Items.SPRUCE_SLAB), new ItemAttributes(1.2, -1), false)
            .add(wrapItemAsHolder(Items.SPRUCE_FENCE), new ItemAttributes(3.5, -1), false)
            .add(wrapItemAsHolder(Items.SPRUCE_FENCE_GATE), new ItemAttributes(5.0, -1), false)
            .add(wrapItemAsHolder(Items.SPRUCE_DOOR), new ItemAttributes(7.5, -1), false)
            .add(wrapItemAsHolder(Items.SPRUCE_TRAPDOOR), new ItemAttributes(3.5, -1), false)
            .add(wrapItemAsHolder(Items.SPRUCE_PRESSURE_PLATE), new ItemAttributes(0.5, -1), false)
            .add(wrapItemAsHolder(Items.SPRUCE_BUTTON), new ItemAttributes(0.1, -1), false)
            .add(wrapItemAsHolder(Items.SPRUCE_SIGN), new ItemAttributes(1.0, -1), false)
            .add(wrapItemAsHolder(Items.BIRCH_WOOD), new ItemAttributes(9.5, -1), false)
            .add(wrapItemAsHolder(Items.STRIPPED_BIRCH_WOOD), new ItemAttributes(8.0, -1), false)
            .add(wrapItemAsHolder(Items.BIRCH_PLANKS), new ItemAttributes(2.5, -1), false)
            .add(wrapItemAsHolder(Items.BIRCH_STAIRS), new ItemAttributes(4.0, -1), false)
            .add(wrapItemAsHolder(Items.BIRCH_SLAB), new ItemAttributes(0.8, -1), false)
            .add(wrapItemAsHolder(Items.BIRCH_FENCE), new ItemAttributes(2.5, -1), false)
            .add(wrapItemAsHolder(Items.BIRCH_FENCE_GATE), new ItemAttributes(4.0, -1), false)
            .add(wrapItemAsHolder(Items.BIRCH_DOOR), new ItemAttributes(6.0, -1), false)
            .add(wrapItemAsHolder(Items.BIRCH_TRAPDOOR), new ItemAttributes(3.0, -1), false)
            .add(wrapItemAsHolder(Items.BIRCH_PRESSURE_PLATE), new ItemAttributes(0.4, -1), false)
            .add(wrapItemAsHolder(Items.BIRCH_BUTTON), new ItemAttributes(0.1, -1), false)
            .add(wrapItemAsHolder(Items.BIRCH_SIGN), new ItemAttributes(1.0, -1), false)
            .add(wrapItemAsHolder(Items.JUNGLE_WOOD), new ItemAttributes(10.0, -1), false)
            .add(wrapItemAsHolder(Items.STRIPPED_JUNGLE_WOOD), new ItemAttributes(9.0, -1), false)
            .add(wrapItemAsHolder(Items.JUNGLE_PLANKS), new ItemAttributes(2.6, -1), false)
            .add(wrapItemAsHolder(Items.JUNGLE_STAIRS), new ItemAttributes(4.5, -1), false)
            .add(wrapItemAsHolder(Items.JUNGLE_SLAB), new ItemAttributes(1.2, -1), false)
            .add(wrapItemAsHolder(Items.JUNGLE_FENCE), new ItemAttributes(3.0, -1), false)
            .add(wrapItemAsHolder(Items.JUNGLE_FENCE_GATE), new ItemAttributes(5.0, -1), false)
            .add(wrapItemAsHolder(Items.JUNGLE_DOOR), new ItemAttributes(7.5, -1), false)
            .add(wrapItemAsHolder(Items.JUNGLE_TRAPDOOR), new ItemAttributes(3.5, -1), false)
            .add(wrapItemAsHolder(Items.JUNGLE_PRESSURE_PLATE), new ItemAttributes(0.5, -1), false)
            .add(wrapItemAsHolder(Items.JUNGLE_BUTTON), new ItemAttributes(0.1, -1), false)
            .add(wrapItemAsHolder(Items.JUNGLE_SIGN), new ItemAttributes(1.0, -1), false)
            .add(wrapItemAsHolder(Items.ACACIA_WOOD), new ItemAttributes(10.0, -1), false)
            .add(wrapItemAsHolder(Items.STRIPPED_ACACIA_WOOD), new ItemAttributes(9.0, -1), false)
            .add(wrapItemAsHolder(Items.ACACIA_PLANKS), new ItemAttributes(2.5, -1), false)
            .add(wrapItemAsHolder(Items.ACACIA_STAIRS), new ItemAttributes(4.0, -1), false)
            .add(wrapItemAsHolder(Items.ACACIA_SLAB), new ItemAttributes(1.0, -1), false)
            .add(wrapItemAsHolder(Items.ACACIA_FENCE), new ItemAttributes(3.0, -1), false)
            .add(wrapItemAsHolder(Items.ACACIA_FENCE_GATE), new ItemAttributes(4.5, -1), false)
            .add(wrapItemAsHolder(Items.ACACIA_DOOR), new ItemAttributes(7.0, -1), false)
            .add(wrapItemAsHolder(Items.ACACIA_TRAPDOOR), new ItemAttributes(3.5, -1), false)
            .add(wrapItemAsHolder(Items.ACACIA_PRESSURE_PLATE), new ItemAttributes(0.5, -1), false)
            .add(wrapItemAsHolder(Items.ACACIA_BUTTON), new ItemAttributes(0.1, -1), false)
            .add(wrapItemAsHolder(Items.ACACIA_SIGN), new ItemAttributes(1.0, -1), false)
            .add(wrapItemAsHolder(Items.DARK_OAK_WOOD), new ItemAttributes(12.0, -1), false)
            .add(wrapItemAsHolder(Items.STRIPPED_DARK_OAK_WOOD), new ItemAttributes(11.0, -1), false)
            .add(wrapItemAsHolder(Items.DARK_OAK_PLANKS), new ItemAttributes(3.0, -1), false)
            .add(wrapItemAsHolder(Items.DARK_OAK_STAIRS), new ItemAttributes(5.0, -1), false)
            .add(wrapItemAsHolder(Items.DARK_OAK_SLAB), new ItemAttributes(1.5, -1), false)
            .add(wrapItemAsHolder(Items.DARK_OAK_FENCE), new ItemAttributes(3.5, -1), false)
            .add(wrapItemAsHolder(Items.DARK_OAK_FENCE_GATE), new ItemAttributes(5.5, -1), false)
            .add(wrapItemAsHolder(Items.DARK_OAK_DOOR), new ItemAttributes(8.0, -1), false)
            .add(wrapItemAsHolder(Items.DARK_OAK_TRAPDOOR), new ItemAttributes(4.0, -1), false)
            .add(wrapItemAsHolder(Items.DARK_OAK_PRESSURE_PLATE), new ItemAttributes(0.6, -1), false)
            .add(wrapItemAsHolder(Items.DARK_OAK_BUTTON), new ItemAttributes(0.1, -1), false)
            .add(wrapItemAsHolder(Items.DARK_OAK_SIGN), new ItemAttributes(1.0, -1), false)
            .add(wrapItemAsHolder(Items.MANGROVE_WOOD), new ItemAttributes(12.0, -1), false)
            .add(wrapItemAsHolder(Items.STRIPPED_MANGROVE_WOOD), new ItemAttributes(10.5, -1), false)
            .add(wrapItemAsHolder(Items.MANGROVE_PLANKS), new ItemAttributes(3.5, -1), false)
            .add(wrapItemAsHolder(Items.MANGROVE_STAIRS), new ItemAttributes(5.5, -1), false)
            .add(wrapItemAsHolder(Items.MANGROVE_SLAB), new ItemAttributes(1.5, -1), false)
            .add(wrapItemAsHolder(Items.MANGROVE_FENCE), new ItemAttributes(4.0, -1), false)
            .add(wrapItemAsHolder(Items.MANGROVE_FENCE_GATE), new ItemAttributes(5.5, -1), false)
            .add(wrapItemAsHolder(Items.MANGROVE_DOOR), new ItemAttributes(8.0, -1), false)
            .add(wrapItemAsHolder(Items.MANGROVE_TRAPDOOR), new ItemAttributes(4.5, -1), false)
            .add(wrapItemAsHolder(Items.MANGROVE_PRESSURE_PLATE), new ItemAttributes(0.7, -1), false)
            .add(wrapItemAsHolder(Items.MANGROVE_BUTTON), new ItemAttributes(0.2, -1), false)
            .add(wrapItemAsHolder(Items.MANGROVE_SIGN), new ItemAttributes(1.5, -1), false)
            .add(wrapItemAsHolder(Items.CHERRY_WOOD), new ItemAttributes(9.0, -1), false)
            .add(wrapItemAsHolder(Items.STRIPPED_CHERRY_WOOD), new ItemAttributes(8.0, -1), false)
            .add(wrapItemAsHolder(Items.CHERRY_PLANKS), new ItemAttributes(2.5, -1), false)
            .add(wrapItemAsHolder(Items.CHERRY_STAIRS), new ItemAttributes(4.0, -1), false)
            .add(wrapItemAsHolder(Items.CHERRY_SLAB), new ItemAttributes(1.0, -1), false)
            .add(wrapItemAsHolder(Items.CHERRY_FENCE), new ItemAttributes(3.0, -1), false)
            .add(wrapItemAsHolder(Items.CHERRY_FENCE_GATE), new ItemAttributes(4.5, -1), false)
            .add(wrapItemAsHolder(Items.CHERRY_DOOR), new ItemAttributes(7.0, -1), false)
            .add(wrapItemAsHolder(Items.CHERRY_TRAPDOOR), new ItemAttributes(3.5, -1), false)
            .add(wrapItemAsHolder(Items.CHERRY_PRESSURE_PLATE), new ItemAttributes(0.6, -1), false)
            .add(wrapItemAsHolder(Items.CHERRY_BUTTON), new ItemAttributes(0.2, -1), false)
            .add(wrapItemAsHolder(Items.CHERRY_SIGN), new ItemAttributes(1.2, -1), false)
            .add(wrapItemAsHolder(Items.BAMBOO_BLOCK), new ItemAttributes(6.0, -1), false)
            .add(wrapItemAsHolder(Items.STRIPPED_BAMBOO_BLOCK), new ItemAttributes(1.8, -1), false)
            .add(wrapItemAsHolder(Items.BAMBOO_PLANKS), new ItemAttributes(0.4, -1), false)
            .add(wrapItemAsHolder(Items.BAMBOO_MOSAIC), new ItemAttributes(0.5, -1), false)
            .add(wrapItemAsHolder(Items.BAMBOO_STAIRS), new ItemAttributes(0.5, -1), false)
            .add(wrapItemAsHolder(Items.BAMBOO_MOSAIC_STAIRS), new ItemAttributes(0.5, -1), false)
            .add(wrapItemAsHolder(Items.BAMBOO_SLAB), new ItemAttributes(0.4, -1), false)
            .add(wrapItemAsHolder(Items.BAMBOO_MOSAIC_SLAB), new ItemAttributes(0.4, -1), false)
            .add(wrapItemAsHolder(Items.BAMBOO_FENCE), new ItemAttributes(0.5, -1), false)
            .add(wrapItemAsHolder(Items.BAMBOO_FENCE_GATE), new ItemAttributes(0.5, -1), false)
            .add(wrapItemAsHolder(Items.BAMBOO_DOOR), new ItemAttributes(0.7, -1), false)
            .add(wrapItemAsHolder(Items.BAMBOO_TRAPDOOR), new ItemAttributes(0.5, -1), false)
            .add(wrapItemAsHolder(Items.BAMBOO_PRESSURE_PLATE), new ItemAttributes(0.4, -1), false)
            .add(wrapItemAsHolder(Items.BAMBOO_BUTTON), new ItemAttributes(0.1, -1), false)
            .add(wrapItemAsHolder(Items.BAMBOO_SIGN), new ItemAttributes(0.3, -1), false)
            .add(wrapItemAsHolder(Items.STRIPPED_CRIMSON_STEM), new ItemAttributes(1.8, -1), false)
            .add(wrapItemAsHolder(Items.CRIMSON_HYPHAE), new ItemAttributes(1.8, -1), false)
            .add(wrapItemAsHolder(Items.STRIPPED_CRIMSON_HYPHAE), new ItemAttributes(1.5, -1), false)
            .add(wrapItemAsHolder(Items.CRIMSON_PLANKS), new ItemAttributes(1.2, -1), false)
            .add(wrapItemAsHolder(Items.CRIMSON_STAIRS), new ItemAttributes(1.2, -1), false)
            .add(wrapItemAsHolder(Items.CRIMSON_SLAB), new ItemAttributes(0.9, -1), false)
            .add(wrapItemAsHolder(Items.CRIMSON_FENCE), new ItemAttributes(1.0, -1), false)
            .add(wrapItemAsHolder(Items.CRIMSON_FENCE_GATE), new ItemAttributes(1.2, -1), false)
            .add(wrapItemAsHolder(Items.CRIMSON_DOOR), new ItemAttributes(1.8, -1), false)
            .add(wrapItemAsHolder(Items.CRIMSON_TRAPDOOR), new ItemAttributes(1.2, -1), false)
            .add(wrapItemAsHolder(Items.CRIMSON_PRESSURE_PLATE), new ItemAttributes(0.7, -1), false)
            .add(wrapItemAsHolder(Items.CRIMSON_BUTTON), new ItemAttributes(0.1, -1), false)
            .add(wrapItemAsHolder(Items.CRIMSON_SIGN), new ItemAttributes(0.4, -1), false)
            .add(wrapItemAsHolder(Items.STRIPPED_WARPED_STEM), new ItemAttributes(1.8, -1), false)
            .add(wrapItemAsHolder(Items.WARPED_HYPHAE), new ItemAttributes(1.8, -1), false)
            .add(wrapItemAsHolder(Items.STRIPPED_WARPED_HYPHAE), new ItemAttributes(1.5, -1), false)
            .add(wrapItemAsHolder(Items.WARPED_PLANKS), new ItemAttributes(1.2, -1), false)
            .add(wrapItemAsHolder(Items.WARPED_STAIRS), new ItemAttributes(1.2, -1), false)
            .add(wrapItemAsHolder(Items.WARPED_SLAB), new ItemAttributes(0.9, -1), false)
            .add(wrapItemAsHolder(Items.WARPED_FENCE), new ItemAttributes(1.0, -1), false)
            .add(wrapItemAsHolder(Items.WARPED_FENCE_GATE), new ItemAttributes(1.2, -1), false)
            .add(wrapItemAsHolder(Items.WARPED_DOOR), new ItemAttributes(1.8, -1), false)
            .add(wrapItemAsHolder(Items.WARPED_TRAPDOOR), new ItemAttributes(1.2, -1), false)
            .add(wrapItemAsHolder(Items.WARPED_PRESSURE_PLATE), new ItemAttributes(0.7, -1), false)
            .add(wrapItemAsHolder(Items.WARPED_BUTTON), new ItemAttributes(0.1, -1), false)
            .add(wrapItemAsHolder(Items.WARPED_SIGN), new ItemAttributes(0.4, -1), false)
            .add(wrapItemAsHolder(Items.STONE_STAIRS), new ItemAttributes(4.5, -1), false)
            .add(wrapItemAsHolder(Items.STONE_SLAB), new ItemAttributes(3.0, -1), false)
            .add(wrapItemAsHolder(Items.STONE_PRESSURE_PLATE), new ItemAttributes(2.0, -1), false)
            .add(wrapItemAsHolder(Items.STONE_BUTTON), new ItemAttributes(0.5, -1), false)
            .add(wrapItemAsHolder(Items.COBBLESTONE), new ItemAttributes(5.0, -1), false)
            .add(wrapItemAsHolder(Items.COBBLESTONE_STAIRS), new ItemAttributes(4.0, -1), false)
            .add(wrapItemAsHolder(Items.COBBLESTONE_SLAB), new ItemAttributes(3.0, -1), false)
            .add(wrapItemAsHolder(Items.COBBLESTONE_WALL), new ItemAttributes(5.0, -1), false)
            .add(wrapItemAsHolder(Items.MOSSY_COBBLESTONE), new ItemAttributes(5.0, -1), false)
            .add(wrapItemAsHolder(Items.MOSSY_COBBLESTONE_STAIRS), new ItemAttributes(4.0, -1), false)
            .add(wrapItemAsHolder(Items.MOSSY_COBBLESTONE_SLAB), new ItemAttributes(2.5, -1), false)
            .add(wrapItemAsHolder(Items.MOSSY_COBBLESTONE_WALL), new ItemAttributes(5.0, -1), false)
            .add(wrapItemAsHolder(Items.SMOOTH_STONE), new ItemAttributes(5.0, -1), false)
            .add(wrapItemAsHolder(Items.SMOOTH_STONE_SLAB), new ItemAttributes(3.5, -1), false)
            .add(wrapItemAsHolder(Items.STONE_BRICKS), new ItemAttributes(6.0, -1), false)
            .add(wrapItemAsHolder(Items.CRACKED_STONE_BRICKS), new ItemAttributes(5.5, -1), false)
            .add(wrapItemAsHolder(Items.STONE_BRICK_STAIRS), new ItemAttributes(5.0, -1), false)
            .add(wrapItemAsHolder(Items.STONE_BRICK_SLAB), new ItemAttributes(4.0, -1), false)
            .add(wrapItemAsHolder(Items.STONE_BRICK_WALL), new ItemAttributes(6.0, -1), false)
            .add(wrapItemAsHolder(Items.CHISELED_STONE_BRICKS), new ItemAttributes(6.0, -1), false)
            .add(wrapItemAsHolder(Items.MOSSY_STONE_BRICKS), new ItemAttributes(6.0, -1), false)
            .add(wrapItemAsHolder(Items.MOSSY_STONE_BRICK_STAIRS), new ItemAttributes(5.0, -1), false)
            .add(wrapItemAsHolder(Items.MOSSY_STONE_BRICK_SLAB), new ItemAttributes(3.5, -1), false)
            .add(wrapItemAsHolder(Items.MOSSY_STONE_BRICK_WALL), new ItemAttributes(6.0, -1), false)
            .add(wrapItemAsHolder(Items.GRANITE_STAIRS), new ItemAttributes(5.5, -1), false)
            .add(wrapItemAsHolder(Items.GRANITE_SLAB), new ItemAttributes(4.5, -1), false)
            .add(wrapItemAsHolder(Items.GRANITE_WALL), new ItemAttributes(6.5, -1), false)
            .add(wrapItemAsHolder(Items.POLISHED_GRANITE), new ItemAttributes(6.5, -1), false)
            .add(wrapItemAsHolder(Items.POLISHED_GRANITE_STAIRS), new ItemAttributes(5.5, -1), false)
            .add(wrapItemAsHolder(Items.POLISHED_GRANITE_SLAB), new ItemAttributes(4.5, -1), false)
            .add(wrapItemAsHolder(Items.DIORITE_STAIRS), new ItemAttributes(5.5, -1), false)
            .add(wrapItemAsHolder(Items.DIORITE_SLAB), new ItemAttributes(4.5, -1), false)
            .add(wrapItemAsHolder(Items.DIORITE_WALL), new ItemAttributes(6.5, -1), false)
            .add(wrapItemAsHolder(Items.POLISHED_DIORITE), new ItemAttributes(6.5, -1), false)
            .add(wrapItemAsHolder(Items.POLISHED_DIORITE_STAIRS), new ItemAttributes(5.5, -1), false)
            .add(wrapItemAsHolder(Items.POLISHED_DIORITE_SLAB), new ItemAttributes(4.5, -1), false)
            .add(wrapItemAsHolder(Items.ANDESITE_STAIRS), new ItemAttributes(6.0, -1), false)
            .add(wrapItemAsHolder(Items.ANDESITE_SLAB), new ItemAttributes(5.0, -1), false)
            .add(wrapItemAsHolder(Items.ANDESITE_WALL), new ItemAttributes(7.0, -1), false)
            .add(wrapItemAsHolder(Items.POLISHED_ANDESITE), new ItemAttributes(7.0, -1), false)
            .add(wrapItemAsHolder(Items.POLISHED_ANDESITE_STAIRS), new ItemAttributes(6.0, -1), false)
            .add(wrapItemAsHolder(Items.POLISHED_ANDESITE_SLAB), new ItemAttributes(5.0, -1), false)
            .add(wrapItemAsHolder(Items.COBBLED_DEEPSLATE), new ItemAttributes(8.0, -1), false)
            .add(wrapItemAsHolder(Items.COBBLED_DEEPSLATE_STAIRS), new ItemAttributes(7.0, -1), false)
            .add(wrapItemAsHolder(Items.COBBLED_DEEPSLATE_SLAB), new ItemAttributes(6.0, -1), false)
            .add(wrapItemAsHolder(Items.COBBLED_DEEPSLATE_WALL), new ItemAttributes(8.0, -1), false)
            .add(wrapItemAsHolder(Items.CHISELED_DEEPSLATE), new ItemAttributes(9.0, -1), false)
            .add(wrapItemAsHolder(Items.POLISHED_DEEPSLATE), new ItemAttributes(8.0, -1), false)
            .add(wrapItemAsHolder(Items.POLISHED_DEEPSLATE_STAIRS), new ItemAttributes(7.0, -1), false)
            .add(wrapItemAsHolder(Items.POLISHED_DEEPSLATE_SLAB), new ItemAttributes(6.0, -1), false)
            .add(wrapItemAsHolder(Items.POLISHED_DEEPSLATE_WALL), new ItemAttributes(8.0, -1), false)
            .add(wrapItemAsHolder(Items.DEEPSLATE_BRICKS), new ItemAttributes(9.0, -1), false)
            .add(wrapItemAsHolder(Items.CRACKED_DEEPSLATE_BRICKS), new ItemAttributes(9.0, -1), false)
            .add(wrapItemAsHolder(Items.DEEPSLATE_BRICK_STAIRS), new ItemAttributes(7.0, -1), false)
            .add(wrapItemAsHolder(Items.DEEPSLATE_BRICK_SLAB), new ItemAttributes(8.0, -1), false)
            .add(wrapItemAsHolder(Items.DEEPSLATE_BRICK_WALL), new ItemAttributes(9.0, -1), false)
            .add(wrapItemAsHolder(Items.DEEPSLATE_TILES), new ItemAttributes(9.0, -1), false)
            .add(wrapItemAsHolder(Items.CRACKED_DEEPSLATE_TILES), new ItemAttributes(9.0, -1), false)
            .add(wrapItemAsHolder(Items.DEEPSLATE_TILE_STAIRS), new ItemAttributes(7.0, -1), false)
            .add(wrapItemAsHolder(Items.DEEPSLATE_TILE_SLAB), new ItemAttributes(8.0, -1), false)
            .add(wrapItemAsHolder(Items.DEEPSLATE_TILE_WALL), new ItemAttributes(9.0, -1), false)
            .add(wrapItemAsHolder(Items.REINFORCED_DEEPSLATE), new ItemAttributes(8.0, -1), false)
            .add(wrapItemAsHolder(Items.TUFF_STAIRS), new ItemAttributes(6.5, -1), false)
            .add(wrapItemAsHolder(Items.TUFF_SLAB), new ItemAttributes(4.5, -1), false)
            .add(wrapItemAsHolder(Items.TUFF_WALL), new ItemAttributes(7.0, -1), false)
            .add(wrapItemAsHolder(Items.CHISELED_TUFF), new ItemAttributes(6.0, -1), false)
            .add(wrapItemAsHolder(Items.POLISHED_TUFF), new ItemAttributes(5.5, -1), false)
            .add(wrapItemAsHolder(Items.POLISHED_TUFF_STAIRS), new ItemAttributes(6.5, -1), false)
            .add(wrapItemAsHolder(Items.POLISHED_TUFF_SLAB), new ItemAttributes(4.5, -1), false)
            .add(wrapItemAsHolder(Items.POLISHED_TUFF_WALL), new ItemAttributes(7.0, -1), false)
            .add(wrapItemAsHolder(Items.TUFF_BRICKS), new ItemAttributes(5.0, -1), false)
            .add(wrapItemAsHolder(Items.TUFF_BRICK_STAIRS), new ItemAttributes(6.0, -1), false)
            .add(wrapItemAsHolder(Items.TUFF_BRICK_SLAB), new ItemAttributes(4.0, -1), false)
            .add(wrapItemAsHolder(Items.TUFF_BRICK_WALL), new ItemAttributes(6.5, -1), false)
            .add(wrapItemAsHolder(Items.CHISELED_TUFF_BRICKS), new ItemAttributes(5.5, -1), false)
            .add(wrapItemAsHolder(Items.BRICKS), new ItemAttributes(4.0, -1), false)
            .add(wrapItemAsHolder(Items.BRICK_STAIRS), new ItemAttributes(5.5, -1), false)
            .add(wrapItemAsHolder(Items.BRICK_SLAB), new ItemAttributes(3.5, -1), false)
            .add(wrapItemAsHolder(Items.BRICK_WALL), new ItemAttributes(6.0, -1), false)
            .add(wrapItemAsHolder(Items.PACKED_MUD), new ItemAttributes(3.0, -1), false)
            .add(wrapItemAsHolder(Items.MUD_BRICKS), new ItemAttributes(4.0, -1), false)
            .add(wrapItemAsHolder(Items.MUD_BRICK_STAIRS), new ItemAttributes(5.0, -1), false)
            .add(wrapItemAsHolder(Items.MUD_BRICK_SLAB), new ItemAttributes(3.5, -1), false)
            .add(wrapItemAsHolder(Items.MUD_BRICK_WALL), new ItemAttributes(5.5, -1), false)
            .add(wrapItemAsHolder(Items.SANDSTONE_STAIRS), new ItemAttributes(5.0, -1), false)
            .add(wrapItemAsHolder(Items.SANDSTONE_SLAB), new ItemAttributes(3.5, -1), false)
            .add(wrapItemAsHolder(Items.SANDSTONE_WALL), new ItemAttributes(5.0, -1), false)
            .add(wrapItemAsHolder(Items.CHISELED_SANDSTONE), new ItemAttributes(4.0, -1), false)
            .add(wrapItemAsHolder(Items.SMOOTH_SANDSTONE), new ItemAttributes(3.5, -1), false)
            .add(wrapItemAsHolder(Items.SMOOTH_SANDSTONE_STAIRS), new ItemAttributes(5.0, -1), false)
            .add(wrapItemAsHolder(Items.SMOOTH_SANDSTONE_SLAB), new ItemAttributes(3.5, -1), false)
            .add(wrapItemAsHolder(Items.CUT_SANDSTONE), new ItemAttributes(5.0, -1), false)
            .add(wrapItemAsHolder(Items.CUT_STANDSTONE_SLAB), new ItemAttributes(4.5, -1), false)
            .add(wrapItemAsHolder(Items.RED_SANDSTONE_STAIRS), new ItemAttributes(5.0, -1), false)
            .add(wrapItemAsHolder(Items.RED_SANDSTONE_SLAB), new ItemAttributes(3.5, -1), false)
            .add(wrapItemAsHolder(Items.RED_SANDSTONE_WALL), new ItemAttributes(5.0, -1), false)
            .add(wrapItemAsHolder(Items.CHISELED_RED_SANDSTONE), new ItemAttributes(4.0, -1), false)
            .add(wrapItemAsHolder(Items.SMOOTH_RED_SANDSTONE), new ItemAttributes(3.5, -1), false)
            .add(wrapItemAsHolder(Items.SMOOTH_RED_SANDSTONE_STAIRS), new ItemAttributes(5.0, -1), false)
            .add(wrapItemAsHolder(Items.SMOOTH_RED_SANDSTONE_SLAB), new ItemAttributes(3.5, -1), false)
            .add(wrapItemAsHolder(Items.CUT_RED_SANDSTONE), new ItemAttributes(5.0, -1), false)
            .add(wrapItemAsHolder(Items.CUT_RED_SANDSTONE_SLAB), new ItemAttributes(4.5, -1), false)
            .add(wrapItemAsHolder(Items.SEA_LANTERN), new ItemAttributes(1.5, -1), false)
            .add(wrapItemAsHolder(Items.PRISMARINE_STAIRS), new ItemAttributes(5.0, -1), false)
            .add(wrapItemAsHolder(Items.PRISMARINE_SLAB), new ItemAttributes(4.0, -1), false)
            .add(wrapItemAsHolder(Items.PRISMARINE_WALL), new ItemAttributes(6.0, -1), false)
            .add(wrapItemAsHolder(Items.PRISMARINE_BRICKS), new ItemAttributes(3.0, -1), false)
            .add(wrapItemAsHolder(Items.PRISMARINE_BRICK_STAIRS), new ItemAttributes(5.0, -1), false)
            .add(wrapItemAsHolder(Items.PRISMARINE_BRICK_SLAB), new ItemAttributes(4.0, -1), false)
            .add(wrapItemAsHolder(Items.DARK_PRISMARINE), new ItemAttributes(4.0, -1), false)
            .add(wrapItemAsHolder(Items.DARK_PRISMARINE_STAIRS), new ItemAttributes(6.0, -1), false)
            .add(wrapItemAsHolder(Items.DARK_PRISMARINE_SLAB), new ItemAttributes(5.0, -1), false)
            .add(wrapItemAsHolder(Items.NETHER_BRICKS), new ItemAttributes(4.0, -1), false)
            .add(wrapItemAsHolder(Items.CRACKED_NETHER_BRICKS), new ItemAttributes(4.0, -1), false)
            .add(wrapItemAsHolder(Items.NETHER_BRICK_STAIRS), new ItemAttributes(5.0, -1), false)
            .add(wrapItemAsHolder(Items.NETHER_BRICK_SLAB), new ItemAttributes(3.5, -1), false)
            .add(wrapItemAsHolder(Items.NETHER_BRICK_WALL), new ItemAttributes(6.0, -1), false)
            .add(wrapItemAsHolder(Items.NETHER_BRICK_FENCE), new ItemAttributes(5.0, -1), false)
            .add(wrapItemAsHolder(Items.CHISELED_NETHER_BRICKS), new ItemAttributes(4.5, -1), false)
            .add(wrapItemAsHolder(Items.RED_NETHER_BRICKS), new ItemAttributes(4.0, -1), false)
            .add(wrapItemAsHolder(Items.RED_NETHER_BRICK_STAIRS), new ItemAttributes(5.0, -1), false)
            .add(wrapItemAsHolder(Items.RED_NETHER_BRICK_SLAB), new ItemAttributes(3.5, -1), false)
            .add(wrapItemAsHolder(Items.RED_NETHER_BRICK_WALL), new ItemAttributes(6.0, -1), false)
            .add(wrapItemAsHolder(Items.POLISHED_BASALT), new ItemAttributes(6.0, -1), false)
            .add(wrapItemAsHolder(Items.GILDED_BLACKSTONE), new ItemAttributes(6.0, -1), false)
            .add(wrapItemAsHolder(Items.BLACKSTONE_STAIRS), new ItemAttributes(6.0, -1), false)
            .add(wrapItemAsHolder(Items.BLACKSTONE_SLAB), new ItemAttributes(4.5, -1), false)
            .add(wrapItemAsHolder(Items.BLACKSTONE_WALL), new ItemAttributes(6.0, -1), false)
            .add(wrapItemAsHolder(Items.CHISELED_POLISHED_BLACKSTONE), new ItemAttributes(6.0, -1), false)
            .add(wrapItemAsHolder(Items.POLISHED_BLACKSTONE), new ItemAttributes(6.0, -1), false)
            .add(wrapItemAsHolder(Items.POLISHED_BLACKSTONE_STAIRS), new ItemAttributes(6.0, -1), false)
            .add(wrapItemAsHolder(Items.POLISHED_BLACKSTONE_SLAB), new ItemAttributes(5.0, -1), false)
            .add(wrapItemAsHolder(Items.POLISHED_BLACKSTONE_WALL), new ItemAttributes(6.0, -1), false)
            .add(wrapItemAsHolder(Items.POLISHED_BLACKSTONE_PRESSURE_PLATE), new ItemAttributes(4.0, -1), false)
            .add(wrapItemAsHolder(Items.POLISHED_BLACKSTONE_BUTTON), new ItemAttributes(3.0, -1), false)
            .add(wrapItemAsHolder(Items.POLISHED_BLACKSTONE_BRICKS), new ItemAttributes(6.0, -1), false)
            .add(wrapItemAsHolder(Items.CRACKED_POLISHED_BLACKSTONE_BRICKS), new ItemAttributes(6.0, -1), false)
            .add(wrapItemAsHolder(Items.POLISHED_BLACKSTONE_BRICK_STAIRS), new ItemAttributes(6.0, -1), false)
            .add(wrapItemAsHolder(Items.POLISHED_BLACKSTONE_BRICK_SLAB), new ItemAttributes(5.0, -1), false)
            .add(wrapItemAsHolder(Items.POLISHED_BLACKSTONE_BRICK_WALL), new ItemAttributes(6.0, -1), false)
            .add(wrapItemAsHolder(Items.END_STONE_BRICKS), new ItemAttributes(5.0, -1), false)
            .add(wrapItemAsHolder(Items.END_STONE_BRICK_STAIRS), new ItemAttributes(5.5, -1), false)
            .add(wrapItemAsHolder(Items.END_STONE_BRICK_SLAB), new ItemAttributes(4.0, -1), false)
            .add(wrapItemAsHolder(Items.END_STONE_BRICK_WALL), new ItemAttributes(5.5, -1), false)
            .add(wrapItemAsHolder(Items.PURPUR_BLOCK), new ItemAttributes(5.0, -1), false)
            .add(wrapItemAsHolder(Items.PURPUR_PILLAR), new ItemAttributes(5.0, -1), false)
            .add(wrapItemAsHolder(Items.PURPUR_STAIRS), new ItemAttributes(5.5, -1), false)
            .add(wrapItemAsHolder(Items.PURPUR_SLAB), new ItemAttributes(4.0, -1), false)
            .add(wrapItemAsHolder(Items.COAL_BLOCK), new ItemAttributes(6.0, -1), false)
            .add(wrapItemAsHolder(Items.IRON_BLOCK), new ItemAttributes(7.0, -1), false)
            .add(wrapItemAsHolder(Items.IRON_BARS), new ItemAttributes(3.5, -1), false)
            .add(wrapItemAsHolder(Items.IRON_DOOR), new ItemAttributes(6.0, -1), false)
            .add(wrapItemAsHolder(Items.IRON_TRAPDOOR), new ItemAttributes(5.5, -1), false)
            .add(wrapItemAsHolder(Items.HEAVY_WEIGHTED_PRESSURE_PLATE), new ItemAttributes(4.5, -1), false)
            .add(wrapItemAsHolder(Items.CHAIN), new ItemAttributes(2.5, -1), false)
            .add(wrapItemAsHolder(Items.GOLD_BLOCK), new ItemAttributes(30.0, -1), false)
            .add(wrapItemAsHolder(Items.LIGHT_WEIGHTED_PRESSURE_PLATE), new ItemAttributes(5.0, -1), false)
            .add(wrapItemAsHolder(Items.REDSTONE_BLOCK), new ItemAttributes(8.0, -1), false)
            .add(wrapItemAsHolder(Items.EMERALD_BLOCK), new ItemAttributes(7.0, -1), false)
            .add(wrapItemAsHolder(Items.LAPIS_BLOCK), new ItemAttributes(6.0, -1), false)
            .add(wrapItemAsHolder(Items.DIAMOND_BLOCK), new ItemAttributes(10.0, -1), false)
            .add(wrapItemAsHolder(Items.NETHERITE_BLOCK), new ItemAttributes(15.0, -1), false)
            .add(wrapItemAsHolder(Items.QUARTZ_BLOCK), new ItemAttributes(4.5, -1), false)
            .add(wrapItemAsHolder(Items.QUARTZ_STAIRS), new ItemAttributes(4.0, -1), false)
            .add(wrapItemAsHolder(Items.QUARTZ_SLAB), new ItemAttributes(3.5, -1), false)
            .add(wrapItemAsHolder(Items.CHISELED_QUARTZ_BLOCK), new ItemAttributes(5.0, -1), false)
            .add(wrapItemAsHolder(Items.QUARTZ_BRICKS), new ItemAttributes(4.5, -1), false)
            .add(wrapItemAsHolder(Items.QUARTZ_PILLAR), new ItemAttributes(5.5, -1), false)
            .add(wrapItemAsHolder(Items.SMOOTH_QUARTZ), new ItemAttributes(5.0, -1), false)
            .add(wrapItemAsHolder(Items.SMOOTH_QUARTZ_STAIRS), new ItemAttributes(4.5, -1), false)
            .add(wrapItemAsHolder(Items.SMOOTH_QUARTZ_SLAB), new ItemAttributes(3.0, -1), false)
            .add(wrapItemAsHolder(Items.AMETHYST_BLOCK), new ItemAttributes(6.0, -1), false)
            .add(wrapItemAsHolder(Items.COPPER_BLOCK), new ItemAttributes(5.0, -1), false)
            .add(wrapItemAsHolder(Items.CHISELED_COPPER), new ItemAttributes(4.0, -1), false)
            .add(wrapItemAsHolder(Items.COPPER_GRATE), new ItemAttributes(3.5, -1), false)
            .add(wrapItemAsHolder(Items.CUT_COPPER), new ItemAttributes(5.0, -1), false)
            .add(wrapItemAsHolder(Items.CUT_COPPER_STAIRS), new ItemAttributes(4.5, -1), false)
            .add(wrapItemAsHolder(Items.CUT_COPPER_SLAB), new ItemAttributes(3.5, -1), false)
            .add(wrapItemAsHolder(Items.COPPER_DOOR), new ItemAttributes(5.0, -1), false)
            .add(wrapItemAsHolder(Items.COPPER_TRAPDOOR), new ItemAttributes(4.0, -1), false)
            .add(wrapItemAsHolder(Items.COPPER_BULB), new ItemAttributes(2.0, -1), false)
            .add(wrapItemAsHolder(Items.EXPOSED_COPPER), new ItemAttributes(5.0, -1), false)
            .add(wrapItemAsHolder(Items.EXPOSED_CHISELED_COPPER), new ItemAttributes(4.0, -1), false)
            .add(wrapItemAsHolder(Items.EXPOSED_COPPER_GRATE), new ItemAttributes(3.5, -1), false)
            .add(wrapItemAsHolder(Items.EXPOSED_CUT_COPPER), new ItemAttributes(5.0, -1), false)
            .add(wrapItemAsHolder(Items.EXPOSED_CUT_COPPER_STAIRS), new ItemAttributes(4.5, -1), false)
            .add(wrapItemAsHolder(Items.EXPOSED_CUT_COPPER_SLAB), new ItemAttributes(3.0, -1), false)
            .add(wrapItemAsHolder(Items.EXPOSED_COPPER_DOOR), new ItemAttributes(5.0, -1), false)
            .add(wrapItemAsHolder(Items.EXPOSED_COPPER_TRAPDOOR), new ItemAttributes(4.0, -1), false)
            .add(wrapItemAsHolder(Items.EXPOSED_COPPER_BULB), new ItemAttributes(2.0, -1), false)
            .add(wrapItemAsHolder(Items.WEATHERED_COPPER), new ItemAttributes(7.0, -1), false)
            .add(wrapItemAsHolder(Items.WEATHERED_CHISELED_COPPER), new ItemAttributes(6.0, -1), false)
            .add(wrapItemAsHolder(Items.WEATHERED_COPPER_GRATE), new ItemAttributes(5.0, -1), false)
            .add(wrapItemAsHolder(Items.WEATHERED_CUT_COPPER), new ItemAttributes(7.0, -1), false)
            .add(wrapItemAsHolder(Items.WEATHERED_CUT_COPPER_STAIRS), new ItemAttributes(6.0, -1), false)
            .add(wrapItemAsHolder(Items.WEATHERED_CUT_COPPER_SLAB), new ItemAttributes(4.0, -1), false)
            .add(wrapItemAsHolder(Items.WEATHERED_COPPER_DOOR), new ItemAttributes(7.0, -1), false)
            .add(wrapItemAsHolder(Items.WEATHERED_COPPER_TRAPDOOR), new ItemAttributes(6.0, -1), false)
            .add(wrapItemAsHolder(Items.WEATHERED_COPPER_BULB), new ItemAttributes(2.5, -1), false)
            .add(wrapItemAsHolder(Items.OXIDIZED_COPPER), new ItemAttributes(7.0, -1), false)
            .add(wrapItemAsHolder(Items.OXIDIZED_CHISELED_COPPER), new ItemAttributes(6.0, -1), false)
            .add(wrapItemAsHolder(Items.OXIDIZED_COPPER_GRATE), new ItemAttributes(5.0, -1), false)
            .add(wrapItemAsHolder(Items.OXIDIZED_CUT_COPPER), new ItemAttributes(7.0, -1), false)
            .add(wrapItemAsHolder(Items.OXIDIZED_CUT_COPPER_STAIRS), new ItemAttributes(6.0, -1), false)
            .add(wrapItemAsHolder(Items.OXIDIZED_CUT_COPPER_SLAB), new ItemAttributes(4.5, -1), false)
            .add(wrapItemAsHolder(Items.OXIDIZED_COPPER_DOOR), new ItemAttributes(7.0, -1), false)
            .add(wrapItemAsHolder(Items.OXIDIZED_COPPER_TRAPDOOR), new ItemAttributes(6.0, -1), false)
            .add(wrapItemAsHolder(Items.OXIDIZED_COPPER_BULB), new ItemAttributes(2.5, -1), false)
            .add(wrapItemAsHolder(Items.WAXED_COPPER_BLOCK), new ItemAttributes(4.5, -1), false)
            .add(wrapItemAsHolder(Items.WAXED_CHISELED_COPPER), new ItemAttributes(3.5, -1), false)
            .add(wrapItemAsHolder(Items.WAXED_COPPER_GRATE), new ItemAttributes(3.0, -1), false)
            .add(wrapItemAsHolder(Items.WAXED_CUT_COPPER), new ItemAttributes(4.5, -1), false)
            .add(wrapItemAsHolder(Items.WAXED_CUT_COPPER_STAIRS), new ItemAttributes(3.5, -1), false)
            .add(wrapItemAsHolder(Items.WAXED_CUT_COPPER_SLAB), new ItemAttributes(3.0, -1), false)
            .add(wrapItemAsHolder(Items.WAXED_COPPER_DOOR), new ItemAttributes(4.5, -1), false)
            .add(wrapItemAsHolder(Items.WAXED_COPPER_TRAPDOOR), new ItemAttributes(3.5, -1), false)
            .add(wrapItemAsHolder(Items.WAXED_COPPER_BULB), new ItemAttributes(2.5, -1), false)
            .add(wrapItemAsHolder(Items.WAXED_EXPOSED_COPPER), new ItemAttributes(5.5, -1), false)
            .add(wrapItemAsHolder(Items.WAXED_EXPOSED_CHISELED_COPPER), new ItemAttributes(4.5, -1), false)
            .add(wrapItemAsHolder(Items.WAXED_EXPOSED_COPPER_GRATE), new ItemAttributes(3.5, -1), false)
            .add(wrapItemAsHolder(Items.WAXED_EXPOSED_CUT_COPPER), new ItemAttributes(5.5, -1), false)
            .add(wrapItemAsHolder(Items.WAXED_EXPOSED_CUT_COPPER_STAIRS), new ItemAttributes(4.5, -1), false)
            .add(wrapItemAsHolder(Items.WAXED_EXPOSED_CUT_COPPER_SLAB), new ItemAttributes(3.5, -1), false)
            .add(wrapItemAsHolder(Items.WAXED_EXPOSED_COPPER_DOOR), new ItemAttributes(5.5, -1), false)
            .add(wrapItemAsHolder(Items.WAXED_EXPOSED_COPPER_TRAPDOOR), new ItemAttributes(4.5, -1), false)
            .add(wrapItemAsHolder(Items.WAXED_EXPOSED_COPPER_BULB), new ItemAttributes(2.5, -1), false)
            .add(wrapItemAsHolder(Items.WAXED_WEATHERED_COPPER), new ItemAttributes(6.0, -1), false)
            .add(wrapItemAsHolder(Items.WAXED_WEATHERED_CHISELED_COPPER), new ItemAttributes(5.0, -1), false)
            .add(wrapItemAsHolder(Items.WAXED_WEATHERED_COPPER_GRATE), new ItemAttributes(4.0, -1), false)
            .add(wrapItemAsHolder(Items.WAXED_WEATHERED_CUT_COPPER), new ItemAttributes(6.0, -1), false)
            .add(wrapItemAsHolder(Items.WAXED_WEATHERED_CUT_COPPER_STAIRS), new ItemAttributes(5.0, -1), false)
            .add(wrapItemAsHolder(Items.WAXED_WEATHERED_CUT_COPPER_SLAB), new ItemAttributes(3.5, -1), false)
            .add(wrapItemAsHolder(Items.WAXED_WEATHERED_COPPER_DOOR), new ItemAttributes(6.0, -1), false)
            .add(wrapItemAsHolder(Items.WAXED_WEATHERED_COPPER_TRAPDOOR), new ItemAttributes(5.0, -1), false)
            .add(wrapItemAsHolder(Items.WAXED_WEATHERED_COPPER_BULB), new ItemAttributes(2.5, -1), false)
            .add(wrapItemAsHolder(Items.WAXED_OXIDIZED_COPPER), new ItemAttributes(7.0, -1), false)
            .add(wrapItemAsHolder(Items.WAXED_OXIDIZED_CHISELED_COPPER), new ItemAttributes(6.0, -1), false)
            .add(wrapItemAsHolder(Items.WAXED_OXIDIZED_COPPER_GRATE), new ItemAttributes(5.0, -1), false)
            .add(wrapItemAsHolder(Items.WAXED_OXIDIZED_CUT_COPPER), new ItemAttributes(7.0, -1), false)
            .add(wrapItemAsHolder(Items.WAXED_OXIDIZED_CUT_COPPER_STAIRS), new ItemAttributes(6.0, -1), false)
            .add(wrapItemAsHolder(Items.WAXED_OXIDIZED_CUT_COPPER_SLAB), new ItemAttributes(4.5, -1), false)
            .add(wrapItemAsHolder(Items.WAXED_OXIDIZED_COPPER_DOOR), new ItemAttributes(7.0, -1), false)
            .add(wrapItemAsHolder(Items.WAXED_OXIDIZED_COPPER_TRAPDOOR), new ItemAttributes(6.0, -1), false)
            .add(wrapItemAsHolder(Items.WAXED_OXIDIZED_COPPER_BULB), new ItemAttributes(2.5, -1), false)

            // Colored blocks...
            .add(wrapItemAsHolder(Items.WHITE_WOOL), new ItemAttributes(0.5, -1), false)
            .add(wrapItemAsHolder(Items.ORANGE_WOOL), new ItemAttributes(0.5, -1), false)
            .add(wrapItemAsHolder(Items.MAGENTA_WOOL), new ItemAttributes(0.5, -1), false)
            .add(wrapItemAsHolder(Items.LIGHT_BLUE_WOOL), new ItemAttributes(0.5, -1), false)
            .add(wrapItemAsHolder(Items.YELLOW_WOOL), new ItemAttributes(0.5, -1), false)
            .add(wrapItemAsHolder(Items.LIME_WOOL), new ItemAttributes(0.5, -1), false)
            .add(wrapItemAsHolder(Items.PINK_WOOL), new ItemAttributes(0.5, -1), false)
            .add(wrapItemAsHolder(Items.GRAY_WOOL), new ItemAttributes(0.5, -1), false)
            .add(wrapItemAsHolder(Items.LIGHT_GRAY_WOOL), new ItemAttributes(0.5, -1), false)
            .add(wrapItemAsHolder(Items.CYAN_WOOL), new ItemAttributes(0.5, -1), false)
            .add(wrapItemAsHolder(Items.PURPLE_WOOL), new ItemAttributes(0.5, -1), false)
            .add(wrapItemAsHolder(Items.BLUE_WOOL), new ItemAttributes(0.5, -1), false)
            .add(wrapItemAsHolder(Items.BROWN_WOOL), new ItemAttributes(0.75, -1), false)
            .add(wrapItemAsHolder(Items.GREEN_WOOL), new ItemAttributes(0.75, -1), false)
            .add(wrapItemAsHolder(Items.RED_WOOL), new ItemAttributes(0.75, -1), false)
            .add(wrapItemAsHolder(Items.BLACK_WOOL), new ItemAttributes(0.75, -1), false)
            .add(wrapItemAsHolder(Items.WHITE_CARPET), new ItemAttributes(0.3, -1), false)
            .add(wrapItemAsHolder(Items.ORANGE_CARPET), new ItemAttributes(0.3, -1), false)
            .add(wrapItemAsHolder(Items.MAGENTA_CARPET), new ItemAttributes(0.3, -1), false)
            .add(wrapItemAsHolder(Items.LIGHT_BLUE_CARPET), new ItemAttributes(0.3, -1), false)
            .add(wrapItemAsHolder(Items.YELLOW_CARPET), new ItemAttributes(0.3, -1), false)
            .add(wrapItemAsHolder(Items.LIME_CARPET), new ItemAttributes(0.3, -1), false)
            .add(wrapItemAsHolder(Items.PINK_CARPET), new ItemAttributes(0.3, -1), false)
            .add(wrapItemAsHolder(Items.GRAY_CARPET), new ItemAttributes(0.3, -1), false)
            .add(wrapItemAsHolder(Items.LIGHT_GRAY_CARPET), new ItemAttributes(0.3, -1), false)
            .add(wrapItemAsHolder(Items.CYAN_CARPET), new ItemAttributes(0.3, -1), false)
            .add(wrapItemAsHolder(Items.PURPLE_CARPET), new ItemAttributes(0.3, -1), false)
            .add(wrapItemAsHolder(Items.BLUE_CARPET), new ItemAttributes(0.3, -1), false)
            .add(wrapItemAsHolder(Items.BROWN_CARPET), new ItemAttributes(0.4, -1), false)
            .add(wrapItemAsHolder(Items.GREEN_CARPET), new ItemAttributes(0.4, -1), false)
            .add(wrapItemAsHolder(Items.RED_CARPET), new ItemAttributes(0.4, -1), false)
            .add(wrapItemAsHolder(Items.BLACK_CARPET), new ItemAttributes(0.4, -1), false)
            .add(wrapItemAsHolder(Items.TERRACOTTA), new ItemAttributes(5.5, -1), false)
            .add(wrapItemAsHolder(Items.WHITE_TERRACOTTA), new ItemAttributes(5.5, -1), false)
            .add(wrapItemAsHolder(Items.ORANGE_TERRACOTTA), new ItemAttributes(5.5, -1), false)
            .add(wrapItemAsHolder(Items.MAGENTA_TERRACOTTA), new ItemAttributes(5.5, -1), false)
            .add(wrapItemAsHolder(Items.LIGHT_BLUE_TERRACOTTA), new ItemAttributes(5.5, -1), false)
            .add(wrapItemAsHolder(Items.YELLOW_TERRACOTTA), new ItemAttributes(5.5, -1), false)
            .add(wrapItemAsHolder(Items.LIME_TERRACOTTA), new ItemAttributes(5.5, -1), false)
            .add(wrapItemAsHolder(Items.PINK_TERRACOTTA), new ItemAttributes(5.5, -1), false)
            .add(wrapItemAsHolder(Items.GRAY_TERRACOTTA), new ItemAttributes(5.5, -1), false)
            .add(wrapItemAsHolder(Items.LIGHT_GRAY_TERRACOTTA), new ItemAttributes(5.5, -1), false)
            .add(wrapItemAsHolder(Items.CYAN_TERRACOTTA), new ItemAttributes(5.5, -1), false)
            .add(wrapItemAsHolder(Items.PURPLE_TERRACOTTA), new ItemAttributes(5.5, -1), false)
            .add(wrapItemAsHolder(Items.BLUE_TERRACOTTA), new ItemAttributes(5.5, -1), false)
            .add(wrapItemAsHolder(Items.BROWN_TERRACOTTA), new ItemAttributes(6.0, -1), false)
            .add(wrapItemAsHolder(Items.GREEN_TERRACOTTA), new ItemAttributes(6.0, -1), false)
            .add(wrapItemAsHolder(Items.RED_TERRACOTTA), new ItemAttributes(6.0, -1), false)
            .add(wrapItemAsHolder(Items.BLACK_TERRACOTTA), new ItemAttributes(6.0, -1), false)
            .add(wrapItemAsHolder(Items.WHITE_CONCRETE), new ItemAttributes(10.0, -1), false)
            .add(wrapItemAsHolder(Items.ORANGE_CONCRETE), new ItemAttributes(10.0, -1), false)
            .add(wrapItemAsHolder(Items.MAGENTA_CONCRETE), new ItemAttributes(10.0, -1), false)
            .add(wrapItemAsHolder(Items.LIGHT_BLUE_CONCRETE), new ItemAttributes(10.0, -1), false)
            .add(wrapItemAsHolder(Items.YELLOW_CONCRETE), new ItemAttributes(10.0, -1), false)
            .add(wrapItemAsHolder(Items.LIME_CONCRETE), new ItemAttributes(10.0, -1), false)
            .add(wrapItemAsHolder(Items.PINK_CONCRETE), new ItemAttributes(10.0, -1), false)
            .add(wrapItemAsHolder(Items.GRAY_CONCRETE), new ItemAttributes(10.0, -1), false)
            .add(wrapItemAsHolder(Items.LIGHT_GRAY_CONCRETE), new ItemAttributes(10.0, -1), false)
            .add(wrapItemAsHolder(Items.CYAN_CONCRETE), new ItemAttributes(10.0, -1), false)
            .add(wrapItemAsHolder(Items.PURPLE_CONCRETE), new ItemAttributes(10.0, -1), false)
            .add(wrapItemAsHolder(Items.BLUE_CONCRETE), new ItemAttributes(10.0, -1), false)
            .add(wrapItemAsHolder(Items.BROWN_CONCRETE), new ItemAttributes(10.5, -1), false)
            .add(wrapItemAsHolder(Items.GREEN_CONCRETE), new ItemAttributes(10.5, -1), false)
            .add(wrapItemAsHolder(Items.RED_CONCRETE), new ItemAttributes(10.5, -1), false)
            .add(wrapItemAsHolder(Items.BLACK_CONCRETE), new ItemAttributes(10.5, -1), false)
            .add(wrapItemAsHolder(Items.WHITE_CONCRETE_POWDER), new ItemAttributes(5.5, -1), false)
            .add(wrapItemAsHolder(Items.ORANGE_CONCRETE_POWDER), new ItemAttributes(5.5, -1), false)
            .add(wrapItemAsHolder(Items.MAGENTA_CONCRETE_POWDER), new ItemAttributes(5.5, -1), false)
            .add(wrapItemAsHolder(Items.LIGHT_BLUE_CONCRETE_POWDER), new ItemAttributes(5.5, -1), false)
            .add(wrapItemAsHolder(Items.YELLOW_CONCRETE_POWDER), new ItemAttributes(5.5, -1), false)
            .add(wrapItemAsHolder(Items.LIME_CONCRETE_POWDER), new ItemAttributes(5.5, -1), false)
            .add(wrapItemAsHolder(Items.PINK_CONCRETE_POWDER), new ItemAttributes(5.5, -1), false)
            .add(wrapItemAsHolder(Items.GRAY_CONCRETE_POWDER), new ItemAttributes(5.5, -1), false)
            .add(wrapItemAsHolder(Items.LIGHT_GRAY_CONCRETE_POWDER), new ItemAttributes(5.5, -1), false)
            .add(wrapItemAsHolder(Items.CYAN_CONCRETE_POWDER), new ItemAttributes(5.5, -1), false)
            .add(wrapItemAsHolder(Items.PURPLE_CONCRETE_POWDER), new ItemAttributes(5.5, -1), false)
            .add(wrapItemAsHolder(Items.BLUE_CONCRETE_POWDER), new ItemAttributes(5.5, -1), false)
            .add(wrapItemAsHolder(Items.BROWN_CONCRETE_POWDER), new ItemAttributes(5.7, -1), false)
            .add(wrapItemAsHolder(Items.GREEN_CONCRETE_POWDER), new ItemAttributes(5.7, -1), false)
            .add(wrapItemAsHolder(Items.RED_CONCRETE_POWDER), new ItemAttributes(5.7, -1), false)
            .add(wrapItemAsHolder(Items.BLACK_CONCRETE_POWDER), new ItemAttributes(5.7, -1), false)
            .add(wrapItemAsHolder(Items.WHITE_GLAZED_TERRACOTTA), new ItemAttributes(6.0, -1), false)
            .add(wrapItemAsHolder(Items.ORANGE_GLAZED_TERRACOTTA), new ItemAttributes(6.0, -1), false)
            .add(wrapItemAsHolder(Items.MAGENTA_GLAZED_TERRACOTTA), new ItemAttributes(6.0, -1), false)
            .add(wrapItemAsHolder(Items.LIGHT_BLUE_GLAZED_TERRACOTTA), new ItemAttributes(6.0, -1), false)
            .add(wrapItemAsHolder(Items.YELLOW_GLAZED_TERRACOTTA), new ItemAttributes(6.0, -1), false)
            .add(wrapItemAsHolder(Items.LIME_GLAZED_TERRACOTTA), new ItemAttributes(6.0, -1), false)
            .add(wrapItemAsHolder(Items.PINK_GLAZED_TERRACOTTA), new ItemAttributes(6.0, -1), false)
            .add(wrapItemAsHolder(Items.GRAY_GLAZED_TERRACOTTA), new ItemAttributes(6.0, -1), false)
            .add(wrapItemAsHolder(Items.LIGHT_GRAY_GLAZED_TERRACOTTA), new ItemAttributes(6.0, -1), false)
            .add(wrapItemAsHolder(Items.CYAN_GLAZED_TERRACOTTA), new ItemAttributes(6.0, -1), false)
            .add(wrapItemAsHolder(Items.PURPLE_GLAZED_TERRACOTTA), new ItemAttributes(6.0, -1), false)
            .add(wrapItemAsHolder(Items.BLUE_GLAZED_TERRACOTTA), new ItemAttributes(6.0, -1), false)
            .add(wrapItemAsHolder(Items.BROWN_GLAZED_TERRACOTTA), new ItemAttributes(6.5, -1), false)
            .add(wrapItemAsHolder(Items.GREEN_GLAZED_TERRACOTTA), new ItemAttributes(6.5, -1), false)
            .add(wrapItemAsHolder(Items.RED_GLAZED_TERRACOTTA), new ItemAttributes(6.5, -1), false)
            .add(wrapItemAsHolder(Items.BLACK_GLAZED_TERRACOTTA), new ItemAttributes(6.5, -1), false)
            .add(wrapItemAsHolder(Items.GLASS), new ItemAttributes(3.0, -1), false)
            .add(wrapItemAsHolder(Items.TINTED_GLASS), new ItemAttributes(2.8, -1), false)
            .add(wrapItemAsHolder(Items.WHITE_STAINED_GLASS), new ItemAttributes(3.1, -1), false)
            .add(wrapItemAsHolder(Items.ORANGE_STAINED_GLASS), new ItemAttributes(3.1, -1), false)
            .add(wrapItemAsHolder(Items.MAGENTA_STAINED_GLASS), new ItemAttributes(3.1, -1), false)
            .add(wrapItemAsHolder(Items.LIGHT_BLUE_STAINED_GLASS), new ItemAttributes(3.1, -1), false)
            .add(wrapItemAsHolder(Items.YELLOW_STAINED_GLASS), new ItemAttributes(3.1, -1), false)
            .add(wrapItemAsHolder(Items.LIME_STAINED_GLASS), new ItemAttributes(3.1, -1), false)
            .add(wrapItemAsHolder(Items.PINK_STAINED_GLASS), new ItemAttributes(3.1, -1), false)
            .add(wrapItemAsHolder(Items.GRAY_STAINED_GLASS), new ItemAttributes(3.1, -1), false)
            .add(wrapItemAsHolder(Items.LIGHT_GRAY_STAINED_GLASS), new ItemAttributes(3.1, -1), false)
            .add(wrapItemAsHolder(Items.CYAN_STAINED_GLASS), new ItemAttributes(3.1, -1), false)
            .add(wrapItemAsHolder(Items.PURPLE_STAINED_GLASS), new ItemAttributes(3.1, -1), false)
            .add(wrapItemAsHolder(Items.BLUE_STAINED_GLASS), new ItemAttributes(3.1, -1), false)
            .add(wrapItemAsHolder(Items.BROWN_STAINED_GLASS), new ItemAttributes(3.2, -1), false)
            .add(wrapItemAsHolder(Items.GREEN_STAINED_GLASS), new ItemAttributes(3.2, -1), false)
            .add(wrapItemAsHolder(Items.RED_STAINED_GLASS), new ItemAttributes(3.2, -1), false)
            .add(wrapItemAsHolder(Items.BLACK_STAINED_GLASS), new ItemAttributes(3.2, -1), false)
            .add(wrapItemAsHolder(Items.GLASS_PANE), new ItemAttributes(0.5, -1), false)
            .add(wrapItemAsHolder(Items.WHITE_STAINED_GLASS_PANE), new ItemAttributes(0.6, -1), false)
            .add(wrapItemAsHolder(Items.ORANGE_STAINED_GLASS_PANE), new ItemAttributes(0.6, -1), false)
            .add(wrapItemAsHolder(Items.MAGENTA_STAINED_GLASS_PANE), new ItemAttributes(0.6, -1), false)
            .add(wrapItemAsHolder(Items.LIGHT_BLUE_STAINED_GLASS_PANE), new ItemAttributes(0.6, -1), false)
            .add(wrapItemAsHolder(Items.YELLOW_STAINED_GLASS_PANE), new ItemAttributes(0.6, -1), false)
            .add(wrapItemAsHolder(Items.LIME_STAINED_GLASS_PANE), new ItemAttributes(0.6, -1), false)
            .add(wrapItemAsHolder(Items.PINK_STAINED_GLASS_PANE), new ItemAttributes(0.6, -1), false)
            .add(wrapItemAsHolder(Items.GRAY_STAINED_GLASS_PANE), new ItemAttributes(0.6, -1), false)
            .add(wrapItemAsHolder(Items.LIGHT_GRAY_STAINED_GLASS_PANE), new ItemAttributes(0.6, -1), false)
            .add(wrapItemAsHolder(Items.CYAN_STAINED_GLASS_PANE), new ItemAttributes(0.6, -1), false)
            .add(wrapItemAsHolder(Items.PURPLE_STAINED_GLASS_PANE), new ItemAttributes(0.6, -1), false)
            .add(wrapItemAsHolder(Items.BLUE_STAINED_GLASS_PANE), new ItemAttributes(0.6, -1), false)
            .add(wrapItemAsHolder(Items.BROWN_STAINED_GLASS_PANE), new ItemAttributes(0.6, -1), false)
            .add(wrapItemAsHolder(Items.GREEN_STAINED_GLASS_PANE), new ItemAttributes(0.6, -1), false)
            .add(wrapItemAsHolder(Items.RED_STAINED_GLASS_PANE), new ItemAttributes(0.6, -1), false)
            .add(wrapItemAsHolder(Items.BLACK_STAINED_GLASS_PANE), new ItemAttributes(0.6, -1), false)
            .add(wrapItemAsHolder(Items.SHULKER_BOX), new ItemAttributes(2.5, -1), false)
            .add(wrapItemAsHolder(Items.WHITE_SHULKER_BOX), new ItemAttributes(2.5, -1), false)
            .add(wrapItemAsHolder(Items.ORANGE_SHULKER_BOX), new ItemAttributes(2.5, -1), false)
            .add(wrapItemAsHolder(Items.MAGENTA_SHULKER_BOX), new ItemAttributes(2.5, -1), false)
            .add(wrapItemAsHolder(Items.LIGHT_BLUE_SHULKER_BOX), new ItemAttributes(2.5, -1), false)
            .add(wrapItemAsHolder(Items.YELLOW_SHULKER_BOX), new ItemAttributes(2.5, -1), false)
            .add(wrapItemAsHolder(Items.LIME_SHULKER_BOX), new ItemAttributes(2.5, -1), false)
            .add(wrapItemAsHolder(Items.PINK_SHULKER_BOX), new ItemAttributes(2.5, -1), false)
            .add(wrapItemAsHolder(Items.GRAY_SHULKER_BOX), new ItemAttributes(2.5, -1), false)
            .add(wrapItemAsHolder(Items.LIGHT_GRAY_SHULKER_BOX), new ItemAttributes(2.5, -1), false)
            .add(wrapItemAsHolder(Items.CYAN_SHULKER_BOX), new ItemAttributes(2.5, -1), false)
            .add(wrapItemAsHolder(Items.PURPLE_SHULKER_BOX), new ItemAttributes(2.5, -1), false)
            .add(wrapItemAsHolder(Items.BLUE_SHULKER_BOX), new ItemAttributes(2.5, -1), false)
            .add(wrapItemAsHolder(Items.BROWN_SHULKER_BOX), new ItemAttributes(2.5, -1), false)
            .add(wrapItemAsHolder(Items.GREEN_SHULKER_BOX), new ItemAttributes(2.5, -1), false)
            .add(wrapItemAsHolder(Items.RED_SHULKER_BOX), new ItemAttributes(2.5, -1), false)
            .add(wrapItemAsHolder(Items.BLACK_SHULKER_BOX), new ItemAttributes(2.5, -1), false)
            .add(wrapItemAsHolder(Items.WHITE_BED), new ItemAttributes(5.0, -1), false)
            .add(wrapItemAsHolder(Items.ORANGE_BED), new ItemAttributes(5.0, -1), false)
            .add(wrapItemAsHolder(Items.MAGENTA_BED), new ItemAttributes(5.0, -1), false)
            .add(wrapItemAsHolder(Items.LIGHT_BLUE_BED), new ItemAttributes(5.0, -1), false)
            .add(wrapItemAsHolder(Items.YELLOW_BED), new ItemAttributes(5.0, -1), false)
            .add(wrapItemAsHolder(Items.LIME_BED), new ItemAttributes(5.0, -1), false)
            .add(wrapItemAsHolder(Items.PINK_BED), new ItemAttributes(5.0, -1), false)
            .add(wrapItemAsHolder(Items.GRAY_BED), new ItemAttributes(5.5, -1), false)
            .add(wrapItemAsHolder(Items.LIGHT_GRAY_BED), new ItemAttributes(5.0, -1), false)
            .add(wrapItemAsHolder(Items.CYAN_BED), new ItemAttributes(5.0, -1), false)
            .add(wrapItemAsHolder(Items.PURPLE_BED), new ItemAttributes(5.0, -1), false)
            .add(wrapItemAsHolder(Items.BLUE_BED), new ItemAttributes(5.0, -1), false)
            .add(wrapItemAsHolder(Items.BROWN_BED), new ItemAttributes(5.5, -1), false)
            .add(wrapItemAsHolder(Items.GREEN_BED), new ItemAttributes(5.0, -1), false)
            .add(wrapItemAsHolder(Items.RED_BED), new ItemAttributes(5.0, -1), false)
            .add(wrapItemAsHolder(Items.BLACK_BED), new ItemAttributes(5.5, -1), false)
            .add(wrapItemAsHolder(Items.CANDLE), new ItemAttributes(0.1, -1), false)
            .add(wrapItemAsHolder(Items.WHITE_CANDLE), new ItemAttributes(0.1, -1), false)
            .add(wrapItemAsHolder(Items.ORANGE_CANDLE), new ItemAttributes(0.1, -1), false)
            .add(wrapItemAsHolder(Items.MAGENTA_CANDLE), new ItemAttributes(0.1, -1), false)
            .add(wrapItemAsHolder(Items.LIGHT_BLUE_CANDLE), new ItemAttributes(0.1, -1), false)
            .add(wrapItemAsHolder(Items.YELLOW_CANDLE), new ItemAttributes(0.1, -1), false)
            .add(wrapItemAsHolder(Items.LIME_CANDLE), new ItemAttributes(0.1, -1), false)
            .add(wrapItemAsHolder(Items.PINK_CANDLE), new ItemAttributes(0.1, -1), false)
            .add(wrapItemAsHolder(Items.GRAY_CANDLE), new ItemAttributes(0.1, -1), false)
            .add(wrapItemAsHolder(Items.LIGHT_GRAY_CANDLE), new ItemAttributes(0.1, -1), false)
            .add(wrapItemAsHolder(Items.CYAN_CANDLE), new ItemAttributes(0.1, -1), false)
            .add(wrapItemAsHolder(Items.PURPLE_CANDLE), new ItemAttributes(0.1, -1), false)
            .add(wrapItemAsHolder(Items.BLUE_CANDLE), new ItemAttributes(0.1, -1), false)
            .add(wrapItemAsHolder(Items.BROWN_CANDLE), new ItemAttributes(0.1, -1), false)
            .add(wrapItemAsHolder(Items.GREEN_CANDLE), new ItemAttributes(0.1, -1), false)
            .add(wrapItemAsHolder(Items.RED_CANDLE), new ItemAttributes(0.1, -1), false)
            .add(wrapItemAsHolder(Items.BLACK_CANDLE), new ItemAttributes(0.1, -1), false)
            .add(wrapItemAsHolder(Items.WHITE_BANNER), new ItemAttributes(0.8, -1), false)
            .add(wrapItemAsHolder(Items.ORANGE_BANNER), new ItemAttributes(0.8, -1), false)
            .add(wrapItemAsHolder(Items.MAGENTA_BANNER), new ItemAttributes(0.8, -1), false)
            .add(wrapItemAsHolder(Items.LIGHT_BLUE_BANNER), new ItemAttributes(0.8, -1), false)
            .add(wrapItemAsHolder(Items.YELLOW_BANNER), new ItemAttributes(0.8, -1), false)
            .add(wrapItemAsHolder(Items.LIME_BANNER), new ItemAttributes(0.8, -1), false)
            .add(wrapItemAsHolder(Items.PINK_BANNER), new ItemAttributes(0.8, -1), false)
            .add(wrapItemAsHolder(Items.GRAY_BANNER), new ItemAttributes(0.8, -1), false)
            .add(wrapItemAsHolder(Items.LIGHT_GRAY_BANNER), new ItemAttributes(0.8, -1), false)
            .add(wrapItemAsHolder(Items.CYAN_BANNER), new ItemAttributes(0.8, -1), false)
            .add(wrapItemAsHolder(Items.PURPLE_BANNER), new ItemAttributes(0.8, -1), false)
            .add(wrapItemAsHolder(Items.BLUE_BANNER), new ItemAttributes(0.8, -1), false)
            .add(wrapItemAsHolder(Items.BROWN_BANNER), new ItemAttributes(0.8, -1), false)
            .add(wrapItemAsHolder(Items.GREEN_BANNER), new ItemAttributes(0.8, -1), false)
            .add(wrapItemAsHolder(Items.RED_BANNER), new ItemAttributes(0.8, -1), false)
            .add(wrapItemAsHolder(Items.BLACK_BANNER), new ItemAttributes(0.8, -1), false)

            // Natural blocks...
            .add(wrapItemAsHolder(Items.GRASS_BLOCK), new ItemAttributes(10.0, -1), false)
            .add(wrapItemAsHolder(Items.PODZOL), new ItemAttributes(9.0, -1), false)
            .add(wrapItemAsHolder(Items.MYCELIUM), new ItemAttributes(9.5, -1), false)
            .add(wrapItemAsHolder(Items.DIRT_PATH), new ItemAttributes(7.0, -1), false)
            .add(wrapItemAsHolder(Items.DIRT), new ItemAttributes(7.5, -1), false)
            .add(wrapItemAsHolder(Items.COARSE_DIRT), new ItemAttributes(8.0, -1), false)
            .add(wrapItemAsHolder(Items.ROOTED_DIRT), new ItemAttributes(9.5, -1), false)
            .add(wrapItemAsHolder(Items.FARMLAND), new ItemAttributes(9.0, -1), false)
            .add(wrapItemAsHolder(Items.MUD), new ItemAttributes(8.5, -1), false)
            .add(wrapItemAsHolder(Items.CLAY), new ItemAttributes(5.5, -1), false)
            .add(wrapItemAsHolder(Items.GRAVEL), new ItemAttributes(7.0, -1), false)
            .add(wrapItemAsHolder(Items.SAND), new ItemAttributes(6.0, -1), false)
            .add(wrapItemAsHolder(Items.SANDSTONE), new ItemAttributes(7.5, -1), false)
            .add(wrapItemAsHolder(Items.RED_SAND), new ItemAttributes(6.0, -1), false)
            .add(wrapItemAsHolder(Items.RED_SANDSTONE), new ItemAttributes(7.5, -1), false)
            .add(wrapItemAsHolder(Items.ICE), new ItemAttributes(5.0, -1), false)
            .add(wrapItemAsHolder(Items.PACKED_ICE), new ItemAttributes(7.0, -1), false)
            .add(wrapItemAsHolder(Items.BLUE_ICE), new ItemAttributes(7.5, -1), false)
            .add(wrapItemAsHolder(Items.SNOW_BLOCK), new ItemAttributes(5.5, -1), false)
            .add(wrapItemAsHolder(Items.SNOW), new ItemAttributes(4.0, -1), false)
            .add(wrapItemAsHolder(Items.MOSS_BLOCK), new ItemAttributes(4.5, -1), false)
            .add(wrapItemAsHolder(Items.MOSS_CARPET), new ItemAttributes(3.5, -1), false)
            .add(wrapItemAsHolder(Items.STONE), new ItemAttributes(5.0, -1), false)
            .add(wrapItemAsHolder(Items.DEEPSLATE), new ItemAttributes(6.5, -1), false)
            .add(wrapItemAsHolder(Items.GRANITE), new ItemAttributes(5.5, -1), false)
            .add(wrapItemAsHolder(Items.DIORITE), new ItemAttributes(5.5, -1), false)
            .add(wrapItemAsHolder(Items.ANDESITE), new ItemAttributes(5.5, -1), false)
            .add(wrapItemAsHolder(Items.CALCITE), new ItemAttributes(5.0, -1), false)
            .add(wrapItemAsHolder(Items.TUFF), new ItemAttributes(5.0, -1), false)
            .add(wrapItemAsHolder(Items.DRIPSTONE_BLOCK), new ItemAttributes(7.5, -1), false)
            .add(wrapItemAsHolder(Items.POINTED_DRIPSTONE), new ItemAttributes(6.0, -1), false)
            .add(wrapItemAsHolder(Items.PRISMARINE), new ItemAttributes(6.5, -1), false)
            .add(wrapItemAsHolder(Items.MAGMA_BLOCK), new ItemAttributes(8.0, -1), false)
            .add(wrapItemAsHolder(Items.OBSIDIAN), new ItemAttributes(10.0, -1), false)
            .add(wrapItemAsHolder(Items.CRYING_OBSIDIAN), new ItemAttributes(10.0, -1), false)
            .add(wrapItemAsHolder(Items.NETHERRACK), new ItemAttributes(4.5, -1), false)
            .add(wrapItemAsHolder(Items.CRIMSON_NYLIUM), new ItemAttributes(5.0, -1), false)
            .add(wrapItemAsHolder(Items.WARPED_NYLIUM), new ItemAttributes(5.0, -1), false)
            .add(wrapItemAsHolder(Items.SOUL_SAND), new ItemAttributes(6.0, -1), false)
            .add(wrapItemAsHolder(Items.SOUL_SOIL), new ItemAttributes(6.0, -1), false)
            .add(wrapItemAsHolder(Items.BONE_BLOCK), new ItemAttributes(7.0, -1), false)
            .add(wrapItemAsHolder(Items.BLACKSTONE), new ItemAttributes(6.5, -1), false)
            .add(wrapItemAsHolder(Items.BASALT), new ItemAttributes(6.5, -1), false)
            .add(wrapItemAsHolder(Items.SMOOTH_BASALT), new ItemAttributes(6.5, -1), false)
            .add(wrapItemAsHolder(Items.SMOOTH_BASALT), new ItemAttributes(6.5, -1), false)
            .add(wrapItemAsHolder(Items.END_STONE), new ItemAttributes(9.0, -1), false)
            .add(wrapItemAsHolder(Items.COAL_ORE), new ItemAttributes(8.0, -1), false)
            .add(wrapItemAsHolder(Items.DEEPSLATE_COAL_ORE), new ItemAttributes(10.0, -1), false)
            .add(wrapItemAsHolder(Items.IRON_ORE), new ItemAttributes(7.5, -1), false)
            .add(wrapItemAsHolder(Items.DEEPSLATE_IRON_ORE), new ItemAttributes(9.5, -1), false)
            .add(wrapItemAsHolder(Items.COPPER_ORE), new ItemAttributes(7.0, -1), false)
            .add(wrapItemAsHolder(Items.DEEPSLATE_COPPER_ORE), new ItemAttributes(9.0, -1), false)
            .add(wrapItemAsHolder(Items.GOLD_ORE), new ItemAttributes(8.0, -1), false)
            .add(wrapItemAsHolder(Items.DEEPSLATE_GOLD_ORE), new ItemAttributes(10.0, -1), false)
            .add(wrapItemAsHolder(Items.REDSTONE_ORE), new ItemAttributes(7.5, -1), false)
            .add(wrapItemAsHolder(Items.DEEPSLATE_REDSTONE_ORE), new ItemAttributes(9.5, -1), false)
            .add(wrapItemAsHolder(Items.EMERALD_ORE), new ItemAttributes(10.0, -1), false)
            .add(wrapItemAsHolder(Items.DEEPSLATE_EMERALD_ORE), new ItemAttributes(11.0, -1), false)
            .add(wrapItemAsHolder(Items.LAPIS_ORE), new ItemAttributes(8.5, -1), false)
            .add(wrapItemAsHolder(Items.DEEPSLATE_LAPIS_ORE), new ItemAttributes(9.5, -1), false)
            .add(wrapItemAsHolder(Items.DIAMOND_ORE), new ItemAttributes(10.5, -1), false)
            .add(wrapItemAsHolder(Items.DEEPSLATE_DIAMOND_ORE), new ItemAttributes(11.5, -1), false)
            .add(wrapItemAsHolder(Items.NETHER_GOLD_ORE), new ItemAttributes(12.5, -1), false)
            .add(wrapItemAsHolder(Items.NETHER_QUARTZ_ORE), new ItemAttributes(10.5, -1), false)
            .add(wrapItemAsHolder(Items.ANCIENT_DEBRIS), new ItemAttributes(30.0, -1), false)
            .add(wrapItemAsHolder(Items.RAW_IRON_BLOCK), new ItemAttributes(24.5, -1), false)
            .add(wrapItemAsHolder(Items.RAW_COPPER_BLOCK), new ItemAttributes(24.0, -1), false)
            .add(wrapItemAsHolder(Items.RAW_GOLD_BLOCK), new ItemAttributes(23.0, -1), false)
            .add(wrapItemAsHolder(Items.GLOWSTONE), new ItemAttributes(7.0, -1), false)
            .add(wrapItemAsHolder(Items.AMETHYST_BLOCK), new ItemAttributes(19.0, -1), false)
            .add(wrapItemAsHolder(Items.BUDDING_AMETHYST), new ItemAttributes(5.5, -1), false)
            .add(wrapItemAsHolder(Items.SMALL_AMETHYST_BUD), new ItemAttributes(1.5, -1), false)
            .add(wrapItemAsHolder(Items.MEDIUM_AMETHYST_BUD), new ItemAttributes(2.5, -1), false)
            .add(wrapItemAsHolder(Items.LARGE_AMETHYST_BUD), new ItemAttributes(3.5, -1), false)
            .add(wrapItemAsHolder(Items.AMETHYST_CLUSTER), new ItemAttributes(4.0, -1), false)
            .add(wrapItemAsHolder(Items.OAK_LOG), new ItemAttributes(8.0, -1), false)
            .add(wrapItemAsHolder(Items.SPRUCE_LOG), new ItemAttributes(8.0, -1), false)
            .add(wrapItemAsHolder(Items.BIRCH_LOG), new ItemAttributes(7.5, -1), false)
            .add(wrapItemAsHolder(Items.JUNGLE_LOG), new ItemAttributes(9.0, -1), false)
            .add(wrapItemAsHolder(Items.ACACIA_LOG), new ItemAttributes(9.0, -1), false)
            .add(wrapItemAsHolder(Items.CHERRY_LOG), new ItemAttributes(8.5, -1), false)
            .add(wrapItemAsHolder(Items.DARK_OAK_LOG), new ItemAttributes(9.5, -1), false)
            .add(wrapItemAsHolder(Items.MANGROVE_LOG), new ItemAttributes(9.0, -1), false)
            .add(wrapItemAsHolder(Items.STRIPPED_OAK_LOG), new ItemAttributes(7.5, -1), false)
            .add(wrapItemAsHolder(Items.STRIPPED_SPRUCE_LOG), new ItemAttributes(7.5, -1), false)
            .add(wrapItemAsHolder(Items.STRIPPED_BIRCH_LOG), new ItemAttributes(7.0, -1), false)
            .add(wrapItemAsHolder(Items.STRIPPED_JUNGLE_LOG), new ItemAttributes(8.5, -1), false)
            .add(wrapItemAsHolder(Items.STRIPPED_ACACIA_LOG), new ItemAttributes(8.5, -1), false)
            .add(wrapItemAsHolder(Items.STRIPPED_CHERRY_LOG), new ItemAttributes(8.0, -1), false)
            .add(wrapItemAsHolder(Items.STRIPPED_DARK_OAK_LOG), new ItemAttributes(9.0, -1), false)
            .add(wrapItemAsHolder(Items.STRIPPED_MANGROVE_LOG), new ItemAttributes(8.5, -1), false)
            .add(wrapItemAsHolder(Items.MANGROVE_ROOTS), new ItemAttributes(3.5, -1), false)
            .add(wrapItemAsHolder(Items.MUDDY_MANGROVE_ROOTS), new ItemAttributes(4.0, -1), false)
            .add(wrapItemAsHolder(Items.MUSHROOM_STEM), new ItemAttributes(6.0, -1), false)
            .add(wrapItemAsHolder(Items.CRIMSON_STEM), new ItemAttributes(7.0, -1), false)
            .add(wrapItemAsHolder(Items.WARPED_STEM), new ItemAttributes(7.0, -1), false)
            .add(wrapItemAsHolder(Items.OAK_LEAVES), new ItemAttributes(0.3, -1), false)
            .add(wrapItemAsHolder(Items.SPRUCE_LEAVES), new ItemAttributes(0.3, -1), false)
            .add(wrapItemAsHolder(Items.BIRCH_LEAVES), new ItemAttributes(0.3, -1), false)
            .add(wrapItemAsHolder(Items.JUNGLE_LEAVES), new ItemAttributes(0.3, -1), false)
            .add(wrapItemAsHolder(Items.ACACIA_LEAVES), new ItemAttributes(0.3, -1), false)
            .add(wrapItemAsHolder(Items.CHERRY_LEAVES), new ItemAttributes(0.3, -1), false)
            .add(wrapItemAsHolder(Items.DARK_OAK_LEAVES), new ItemAttributes(0.3, -1), false)
            .add(wrapItemAsHolder(Items.MANGROVE_LEAVES), new ItemAttributes(0.4, -1), false)
            .add(wrapItemAsHolder(Items.AZALEA_LEAVES), new ItemAttributes(0.4, -1), false)
            .add(wrapItemAsHolder(Items.FLOWERING_AZALEA_LEAVES), new ItemAttributes(0.4, -1), false)
            .add(wrapItemAsHolder(Items.BROWN_MUSHROOM_BLOCK), new ItemAttributes(1.0, -1), false)
            .add(wrapItemAsHolder(Items.RED_MUSHROOM_BLOCK), new ItemAttributes(1.0, -1), false)
            .add(wrapItemAsHolder(Items.NETHER_WART_BLOCK), new ItemAttributes(1.2, -1), false)
            .add(wrapItemAsHolder(Items.WARPED_WART_BLOCK), new ItemAttributes(1.2, -1), false)
            .add(wrapItemAsHolder(Items.SHROOMLIGHT), new ItemAttributes(1.0, -1), false)
            .add(wrapItemAsHolder(Items.OAK_SAPLING), new ItemAttributes(0.1, 2), false)
            .add(wrapItemAsHolder(Items.SPRUCE_SAPLING), new ItemAttributes(0.1, 2), false)
            .add(wrapItemAsHolder(Items.BIRCH_SAPLING), new ItemAttributes(0.1, 2), false)
            .add(wrapItemAsHolder(Items.JUNGLE_SAPLING), new ItemAttributes(0.1, 2), false)
            .add(wrapItemAsHolder(Items.ACACIA_SAPLING), new ItemAttributes(0.1, 2), false)
            .add(wrapItemAsHolder(Items.CHERRY_SAPLING), new ItemAttributes(0.1, 2), false)
            .add(wrapItemAsHolder(Items.DARK_OAK_SAPLING), new ItemAttributes(0.1, 2), false)
            .add(wrapItemAsHolder(Items.MANGROVE_PROPAGULE), new ItemAttributes(0.2, -1), false)
            .add(wrapItemAsHolder(Items.AZALEA), new ItemAttributes(0.15, -1), false)
            .add(wrapItemAsHolder(Items.FLOWERING_AZALEA), new ItemAttributes(0.2, -1), false)
            .add(wrapItemAsHolder(Items.BROWN_MUSHROOM), new ItemAttributes(0.05, 5), false)
            .add(wrapItemAsHolder(Items.RED_MUSHROOM), new ItemAttributes(0.05, 5), false)
            .add(wrapItemAsHolder(Items.CRIMSON_FUNGUS), new ItemAttributes(0.1, 9), false)
            .add(wrapItemAsHolder(Items.WARPED_FUNGUS), new ItemAttributes(0.1, 9), false)
            .add(wrapItemAsHolder(Items.SHORT_GRASS), new ItemAttributes(0.03, 1), false)
            .add(wrapItemAsHolder(Items.FERN), new ItemAttributes(0.05, 1), false)
            .add(wrapItemAsHolder(Items.DEAD_BUSH), new ItemAttributes(0.07, 1), false)
            .add(wrapItemAsHolder(Items.DANDELION), new ItemAttributes(0.02, 2), false)
            .add(wrapItemAsHolder(Items.POPPY), new ItemAttributes(0.02, 3), false)
            .add(wrapItemAsHolder(Items.BLUE_ORCHID), new ItemAttributes(0.02, 5), false)
            .add(wrapItemAsHolder(Items.ALLIUM), new ItemAttributes(0.02, 4), false)
            .add(wrapItemAsHolder(Items.AZURE_BLUET), new ItemAttributes(0.02, 3), false)
            .add(wrapItemAsHolder(Items.ORANGE_TULIP), new ItemAttributes(0.03, 6), false)
            .add(wrapItemAsHolder(Items.PINK_TULIP), new ItemAttributes(0.03, 6), false)
            .add(wrapItemAsHolder(Items.RED_TULIP), new ItemAttributes(0.03, 6), false)
            .add(wrapItemAsHolder(Items.WHITE_TULIP), new ItemAttributes(0.03, 6), false)
            .add(wrapItemAsHolder(Items.OXEYE_DAISY), new ItemAttributes(0.02, 3), false)
            .add(wrapItemAsHolder(Items.CORNFLOWER), new ItemAttributes(0.02, 5), false)
            .add(wrapItemAsHolder(Items.LILY_OF_THE_VALLEY), new ItemAttributes(0.03, 8), false)
            .add(wrapItemAsHolder(Items.TORCHFLOWER), new ItemAttributes(0.03, 10), false)
            .add(wrapItemAsHolder(Items.WITHER_ROSE), new ItemAttributes(0.04, 12), false)
            .add(wrapItemAsHolder(Items.PINK_PETALS), new ItemAttributes(0.02, 7), false)
            .add(wrapItemAsHolder(Items.SPORE_BLOSSOM), new ItemAttributes(0.05, 15), false)
            .add(wrapItemAsHolder(Items.BAMBOO), new ItemAttributes(0.3, 2), false)
            .add(wrapItemAsHolder(Items.SUGAR_CANE), new ItemAttributes(0.5, 3), false)
            .add(wrapItemAsHolder(Items.CACTUS), new ItemAttributes(1.0, -1), false)
            .add(wrapItemAsHolder(Items.CRIMSON_ROOTS), new ItemAttributes(0.7, 8), false)
            .add(wrapItemAsHolder(Items.WARPED_ROOTS), new ItemAttributes(0.7, 8), false)
            .add(wrapItemAsHolder(Items.NETHER_SPROUTS), new ItemAttributes(0.5, 10), false)
            .add(wrapItemAsHolder(Items.WEEPING_VINES), new ItemAttributes(0.4, 12), false)
            .add(wrapItemAsHolder(Items.TWISTING_VINES), new ItemAttributes(0.4, 12), false)
            .add(wrapItemAsHolder(Items.VINE), new ItemAttributes(0.2, 4), false)
            .add(wrapItemAsHolder(Items.TALL_GRASS), new ItemAttributes(0.1, 1), false)
            .add(wrapItemAsHolder(Items.LARGE_FERN), new ItemAttributes(0.3, 3), false)
            .add(wrapItemAsHolder(Items.SUNFLOWER), new ItemAttributes(0.5, 3), false)
            .add(wrapItemAsHolder(Items.LILAC), new ItemAttributes(0.5, 4), false)
            .add(wrapItemAsHolder(Items.ROSE_BUSH), new ItemAttributes(0.5, 5), false)
            .add(wrapItemAsHolder(Items.PEONY), new ItemAttributes(0.5, 4), false)
            .add(wrapItemAsHolder(Items.PITCHER_PLANT), new ItemAttributes(0.6, 8), false)
            .add(wrapItemAsHolder(Items.BIG_DRIPLEAF), new ItemAttributes(1.0, -1), false)
            .add(wrapItemAsHolder(Items.SMALL_DRIPLEAF), new ItemAttributes(0.8, -1), false)
            .add(wrapItemAsHolder(Items.CHORUS_FLOWER), new ItemAttributes(0.7, 12), false)
            .add(wrapItemAsHolder(Items.CHORUS_PLANT), new ItemAttributes(1.5, -1), false)
            .add(wrapItemAsHolder(Items.GLOW_LICHEN), new ItemAttributes(0.3, 10), false)
            .add(wrapItemAsHolder(Items.HANGING_ROOTS), new ItemAttributes(0.4, 8), false)
            .add(wrapItemAsHolder(Items.FROGSPAWN), new ItemAttributes(0.5, 20), false)
            .add(wrapItemAsHolder(Items.TURTLE_EGG), new ItemAttributes(1.0, 25), false)
            .add(wrapItemAsHolder(Items.SNIFFER_EGG), new ItemAttributes(1.5, 40), false)
            .add(wrapItemAsHolder(Items.WHEAT_SEEDS), new ItemAttributes(0.2, 2), false)
            .add(wrapItemAsHolder(Items.COCOA_BEANS), new ItemAttributes(0.1, 3), false)
            .add(wrapItemAsHolder(Items.PUMPKIN_SEEDS), new ItemAttributes(0.05, 1), false)
            .add(wrapItemAsHolder(Items.MELON_SEEDS), new ItemAttributes(0.05, 1), false)
            .add(wrapItemAsHolder(Items.BEETROOT_SEEDS), new ItemAttributes(0.05, 1), false)
            .add(wrapItemAsHolder(Items.TORCHFLOWER_SEEDS), new ItemAttributes(0.05, 6), false)
            .add(wrapItemAsHolder(Items.PITCHER_POD), new ItemAttributes(0.2, 8), false)
            .add(wrapItemAsHolder(Items.NETHER_WART), new ItemAttributes(0.3, 12), false)
            .add(wrapItemAsHolder(Items.LILY_PAD), new ItemAttributes(0.5, 5), false)
            .add(wrapItemAsHolder(Items.SEAGRASS), new ItemAttributes(0.2, 4), false)
            .add(wrapItemAsHolder(Items.SEA_PICKLE), new ItemAttributes(0.2, 8), false)
            .add(wrapItemAsHolder(Items.KELP), new ItemAttributes(0.3, 3), false)
            .add(wrapItemAsHolder(Items.DRIED_KELP_BLOCK), new ItemAttributes(2.0, -1), false)
            .add(wrapItemAsHolder(Items.TUBE_CORAL_BLOCK), new ItemAttributes(4.0, 30), false)
            .add(wrapItemAsHolder(Items.BRAIN_CORAL_BLOCK), new ItemAttributes(4.0, 40), false)
            .add(wrapItemAsHolder(Items.BUBBLE_CORAL_BLOCK), new ItemAttributes(4.0, 35), false)
            .add(wrapItemAsHolder(Items.FIRE_CORAL_BLOCK), new ItemAttributes(4.0, 45), false)
            .add(wrapItemAsHolder(Items.HORN_CORAL_BLOCK), new ItemAttributes(4.0, 25), false)
            .add(wrapItemAsHolder(Items.DEAD_BRAIN_CORAL_BLOCK), new ItemAttributes(3.5, 10), false)
            .add(wrapItemAsHolder(Items.DEAD_BUBBLE_CORAL_BLOCK), new ItemAttributes(3.5, 8), false)
            .add(wrapItemAsHolder(Items.DEAD_FIRE_CORAL_BLOCK), new ItemAttributes(3.5, 12), false)
            .add(wrapItemAsHolder(Items.DEAD_HORN_CORAL_BLOCK), new ItemAttributes(3.5, 6), false)
            .add(wrapItemAsHolder(Items.BRAIN_CORAL), new ItemAttributes(1.0, 15), false)
            .add(wrapItemAsHolder(Items.BUBBLE_CORAL), new ItemAttributes(1.0, 12), false)
            .add(wrapItemAsHolder(Items.FIRE_CORAL), new ItemAttributes(1.0, 20), false)
            .add(wrapItemAsHolder(Items.HORN_CORAL), new ItemAttributes(1.0, 10), false)
            .add(wrapItemAsHolder(Items.DEAD_BRAIN_CORAL), new ItemAttributes(0.8, 5), false)
            .add(wrapItemAsHolder(Items.DEAD_BUBBLE_CORAL), new ItemAttributes(0.8, 4), false)
            .add(wrapItemAsHolder(Items.DEAD_FIRE_CORAL), new ItemAttributes(0.8, 6), false)
            .add(wrapItemAsHolder(Items.DEAD_HORN_CORAL), new ItemAttributes(0.8, 3), false)
            .add(wrapItemAsHolder(Items.BRAIN_CORAL_FAN), new ItemAttributes(0.5, 8), false)
            .add(wrapItemAsHolder(Items.BUBBLE_CORAL_FAN), new ItemAttributes(0.5, 7), false)
            .add(wrapItemAsHolder(Items.FIRE_CORAL_FAN), new ItemAttributes(0.5, 10), false)
            .add(wrapItemAsHolder(Items.HORN_CORAL_FAN), new ItemAttributes(0.5, 6), false)
            .add(wrapItemAsHolder(Items.DEAD_BRAIN_CORAL_FAN), new ItemAttributes(0.3, 2), false)
            .add(wrapItemAsHolder(Items.DEAD_BUBBLE_CORAL_FAN), new ItemAttributes(0.3, 1), false)
            .add(wrapItemAsHolder(Items.DEAD_FIRE_CORAL_FAN), new ItemAttributes(0.3, 3), false)
            .add(wrapItemAsHolder(Items.DEAD_HORN_CORAL_FAN), new ItemAttributes(0.3, 1), false)
            .add(wrapItemAsHolder(Items.SPONGE), new ItemAttributes(0.5, 20), false)
            .add(wrapItemAsHolder(Items.WET_SPONGE), new ItemAttributes(0.8, 25), false)
            .add(wrapItemAsHolder(Items.MELON), new ItemAttributes(2.5, 5), false)
            .add(wrapItemAsHolder(Items.PUMPKIN), new ItemAttributes(3.0, 6), false)
            .add(wrapItemAsHolder(Items.CARVED_PUMPKIN), new ItemAttributes(3.0, 8), false)
            .add(wrapItemAsHolder(Items.JACK_O_LANTERN), new ItemAttributes(3.0, 10), false)
            .add(wrapItemAsHolder(Items.HAY_BLOCK), new ItemAttributes(9.0, 15), false)
            .add(wrapItemAsHolder(Items.BEE_NEST), new ItemAttributes(4.0, 50), false)
            .add(wrapItemAsHolder(Items.HONEYCOMB_BLOCK), new ItemAttributes(5.0, 40), false)
            .add(wrapItemAsHolder(Items.SLIME_BLOCK), new ItemAttributes(4.0, 35), false)
            .add(wrapItemAsHolder(Items.HONEY_BLOCK), new ItemAttributes(4.0, 45), false)
            .add(wrapItemAsHolder(Items.PEARLESCENT_FROGLIGHT), new ItemAttributes(2.5, 20), false)
            .add(wrapItemAsHolder(Items.VERDANT_FROGLIGHT), new ItemAttributes(2.5, 18), false)
            .add(wrapItemAsHolder(Items.OCHRE_FROGLIGHT), new ItemAttributes(2.5, 22), false)
            .add(wrapItemAsHolder(Items.SCULK), new ItemAttributes(4.0, 30), false)
            .add(wrapItemAsHolder(Items.SCULK_VEIN), new ItemAttributes(0.5, 12), false)
            .add(wrapItemAsHolder(Items.SCULK_CATALYST), new ItemAttributes(5.0, 60), false)
            .add(wrapItemAsHolder(Items.SCULK_SHRIEKER), new ItemAttributes(6.0, 75), false)
            .add(wrapItemAsHolder(Items.SCULK_SENSOR), new ItemAttributes(3.0, 50), false)
            .add(wrapItemAsHolder(Items.COBWEB), new ItemAttributes(1.0, 10), false)
            .add(wrapItemAsHolder(Items.BEDROCK), new ItemAttributes(100.0, -1), false)
        ;


        // Food & drinks
        this.builder(FalloutMcDataMaps.FOOD_ATTRIBUTES)
            .add(wrapItemAsHolder(Items.APPLE), new FoodAttributes(5, 3, List.of(new EffectWithDuration(FalloutMcEffects.EXAMPLE_EFFECT.value(), 0)), List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 10, 2, 0.2, false, false, true, 5), false)
            .add(wrapItemAsHolder(Items.BAKED_POTATO), new FoodAttributes(8, 5, List.of(new EffectWithDuration(FalloutMcEffects.EXAMPLE_EFFECT.value(), 0)), List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()),0, 15, 3, 0.4, false, true, false, 6), false)
            .add(wrapItemAsHolder(Items.BEETROOT), new FoodAttributes(3, 6, List.of(new EffectWithDuration(FalloutMcEffects.EXAMPLE_EFFECT.value(), 0)), List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()),0, 5, 1, 0.3, false, false, true, 2), false)
            .add(wrapItemAsHolder(Items.BEEF), new FoodAttributes(15, 6, List.of(new EffectWithDuration(FalloutMcEffects.EXAMPLE_EFFECT.value(), 0)), List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 12, 2, 0.5, false, false, false, 8), false)
            .add(wrapItemAsHolder(Items.BREAD), new FoodAttributes(5, 8, List.of(new EffectWithDuration(FalloutMcEffects.EXAMPLE_EFFECT.value(), 0)), List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 7, 0, 0.4, false, true, false, 5), false)
            .add(wrapItemAsHolder(Items.CAKE), new FoodAttributes(8, 7, List.of(new EffectWithDuration(FalloutMcEffects.EXAMPLE_EFFECT.value(), 0)), List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 18, 5, 0.7, false, true, false, 12), false)
            .add(wrapItemAsHolder(Items.CARROT), new FoodAttributes(2, 2, List.of(new EffectWithDuration(FalloutMcEffects.EXAMPLE_EFFECT.value(), 0)), List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 5, 1, 0.3, false, false, true, 2), false)
            .add(wrapItemAsHolder(Items.CHICKEN), new FoodAttributes(4, 3, List.of(new EffectWithDuration(FalloutMcEffects.EXAMPLE_EFFECT.value(), 0)), List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 6, 1, 0.4, false, false, false, 2), false)
            .add(wrapItemAsHolder(Items.CHORUS_FRUIT), new FoodAttributes(10, 10, List.of(new EffectWithDuration(FalloutMcEffects.EXAMPLE_EFFECT.value(), 0)), List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()),0, 20, 20, 0.4, false, false, false, 33), false)
            .add(wrapItemAsHolder(Items.COD), new FoodAttributes(6, 6, List.of(new EffectWithDuration(FalloutMcEffects.EXAMPLE_EFFECT.value(), 0)), List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 6, 2, 0.5, false, false, false, 4), false)
            .add(wrapItemAsHolder(Items.COOKIE), new FoodAttributes(4, 7, List.of(new EffectWithDuration(FalloutMcEffects.EXAMPLE_EFFECT.value(), 0)), List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 5, 0, 0.15, false, false, false, 12), false)
            .add(wrapItemAsHolder(Items.COOKED_BEEF), new FoodAttributes(8, 6, List.of(new EffectWithDuration(FalloutMcEffects.EXAMPLE_EFFECT.value(), 0)), List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 15, 1, 0.6, false, false, false, 15), false)
            .add(wrapItemAsHolder(Items.COOKED_CHICKEN), new FoodAttributes(5, 6, List.of(new EffectWithDuration(FalloutMcEffects.EXAMPLE_EFFECT.value(), 0)), List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 17, 2, 0.5, false, false, false, 15), false)
            .add(wrapItemAsHolder(Items.COOKED_COD), new FoodAttributes(5, 8, List.of(new EffectWithDuration(FalloutMcEffects.EXAMPLE_EFFECT.value(), 0)), List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 12, 1, 0.4, false, false, false, 15), false)
            .add(wrapItemAsHolder(Items.COOKED_MUTTON), new FoodAttributes(9, 7, List.of(new EffectWithDuration(FalloutMcEffects.EXAMPLE_EFFECT.value(), 0)), List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 13, 1, 0.5, false, false, false, 15), false)
            .add(wrapItemAsHolder(Items.COOKED_PORKCHOP), new FoodAttributes(10, 6, List.of(new EffectWithDuration(FalloutMcEffects.EXAMPLE_EFFECT.value(), 0)), List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 12, 1, 0.6, false, false, false, 15), false)
            .add(wrapItemAsHolder(Items.COOKED_RABBIT), new FoodAttributes(3, 8, List.of(new EffectWithDuration(FalloutMcEffects.EXAMPLE_EFFECT.value(), 0)), List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 10, 2, 0.5, false, false, false, 15), false)
            .add(wrapItemAsHolder(Items.COOKED_SALMON), new FoodAttributes(2, 5, List.of(new EffectWithDuration(FalloutMcEffects.EXAMPLE_EFFECT.value(), 0)), List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 14, 1, 0.4, false, false, false, 15), false)
            .add(wrapItemAsHolder(Items.DRIED_KELP), new FoodAttributes(14, 4, List.of(new EffectWithDuration(FalloutMcEffects.EXAMPLE_EFFECT.value(), 0)), List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 8, 0, 0.1, false, false, false, 4), false)
            .add(wrapItemAsHolder(Items.ENCHANTED_GOLDEN_APPLE), new FoodAttributes(0, 30, List.of(new EffectWithDuration(FalloutMcEffects.EXAMPLE_EFFECT.value(), 0)), List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 30, 30, 3, false, false, false, 100), false)
            .add(wrapItemAsHolder(Items.GLOW_BERRIES), new FoodAttributes(16, 4, List.of(new EffectWithDuration(FalloutMcEffects.EXAMPLE_EFFECT.value(), 0)), List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 6, 4, 0.2, false, false, false, 5), false)
            .add(wrapItemAsHolder(Items.GOLDEN_APPLE), new FoodAttributes(2, 19, List.of(new EffectWithDuration(FalloutMcEffects.EXAMPLE_EFFECT.value(), 0)), List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 12, 14, 2, false, false, false, 50), false)
            .add(wrapItemAsHolder(Items.GOLDEN_CARROT), new FoodAttributes(2, 15, List.of(new EffectWithDuration(FalloutMcEffects.EXAMPLE_EFFECT.value(), 0)), List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 11, 3, 0.5, false, false, false, 33), false)
            .add(wrapItemAsHolder(Items.HONEY_BOTTLE), new FoodAttributes(7, 3, List.of(new EffectWithDuration(FalloutMcEffects.EXAMPLE_EFFECT.value(), 0)), List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 12, 3, 0.5, false, false, false, 12), false)
            .add(wrapItemAsHolder(Items.MELON_SLICE), new FoodAttributes(3, 2, List.of(new EffectWithDuration(FalloutMcEffects.EXAMPLE_EFFECT.value(), 0)), List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 4, 15, 0.25, false, false, false, 2), false)
            .add(wrapItemAsHolder(Items.MILK_BUCKET), new FoodAttributes(4, 6, List.of(new EffectWithDuration(FalloutMcEffects.EXAMPLE_EFFECT.value(), 0)), List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 2, 20, 1, false, false, false, 6), false)
            .add(wrapItemAsHolder(Items.MUTTON), new FoodAttributes(11, 6, List.of(new EffectWithDuration(FalloutMcEffects.EXAMPLE_EFFECT.value(), 0)), List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 11, 1, 0.5, false, false, false, 5), false)
            .add(wrapItemAsHolder(Items.POISONOUS_POTATO), new FoodAttributes(25, 0, List.of(new EffectWithDuration(FalloutMcEffects.EXAMPLE_EFFECT.value(), 0)), List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 4, 1, 0.2, false, false, false, 1), false)
            .add(wrapItemAsHolder(Items.PORKCHOP), new FoodAttributes(12, 4, List.of(new EffectWithDuration(FalloutMcEffects.EXAMPLE_EFFECT.value(), 0)), List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 9, 2, 0.6, false, false, false, 7), false)
            .add(wrapItemAsHolder(Items.POTATO), new FoodAttributes(10, 4, List.of(new EffectWithDuration(FalloutMcEffects.EXAMPLE_EFFECT.value(), 0)), List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 11, 0, 0.3, false, false, false, 4), false)
            .add(wrapItemAsHolder(Items.PUMPKIN_PIE), new FoodAttributes(6, 7, List.of(new EffectWithDuration(FalloutMcEffects.EXAMPLE_EFFECT.value(), 0)), List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 15, 1, 0.7, false, false, false, 15), false)
            .add(wrapItemAsHolder(Items.PUFFERFISH), new FoodAttributes(12, 1, List.of(new EffectWithDuration(FalloutMcEffects.EXAMPLE_EFFECT.value(), 0)), List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 3, 10, 0.5, false, false, false, 4), false)
            .add(wrapItemAsHolder(Items.RABBIT), new FoodAttributes(9, 3, List.of(new EffectWithDuration(FalloutMcEffects.EXAMPLE_EFFECT.value(), 0)), List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 8, 1, 0.5, false, false, false, 0), false)
            .add(wrapItemAsHolder(Items.ROTTEN_FLESH), new FoodAttributes(35, 1, List.of(new EffectWithDuration(FalloutMcEffects.EXAMPLE_EFFECT.value(), 0)), List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 5, 0, 0.5, false, false, false, 1), false)
            .add(wrapItemAsHolder(Items.SALMON), new FoodAttributes(4, 4, List.of(new EffectWithDuration(FalloutMcEffects.EXAMPLE_EFFECT.value(), 0)), List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 6, 3, 0.5, false, false, false, 5), false)
            .add(wrapItemAsHolder(Items.SPIDER_EYE), new FoodAttributes(15, 1, List.of(new EffectWithDuration(FalloutMcEffects.EXAMPLE_EFFECT.value(), 0)), List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 7, 2, 0.25, false, false, false, 3), false)
            .add(wrapItemAsHolder(Items.SWEET_BERRIES), new FoodAttributes(9, 3, List.of(new EffectWithDuration(FalloutMcEffects.EXAMPLE_EFFECT.value(), 0)), List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 5, 3, 0.2, false, false, false, 4), false)
            .add(wrapItemAsHolder(Items.TROPICAL_FISH), new FoodAttributes(13, 4, List.of(new EffectWithDuration(FalloutMcEffects.EXAMPLE_EFFECT.value(), 0)), List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 7, 6, 0.3, false, false, false, 6), false)
            .add(wrapItemAsHolder(Items.WHEAT), new FoodAttributes(14, 2, List.of(new EffectWithDuration(FalloutMcEffects.EXAMPLE_EFFECT.value(), 0)), List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 2, 0, 0.25, false, false, false, 1), false);

        this.builder(FalloutMcDataMaps.SOUP_ATTRIBUTES)
            .add(wrapItemAsHolder(Items.BEETROOT_SOUP), new SoupAttributes(5, 8, List.of(new EffectWithDuration(FalloutMcEffects.EXAMPLE_EFFECT.value(), 0)), List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 10, 15, 0.5, true, 5), false)
            .add(wrapItemAsHolder(Items.MUSHROOM_STEW), new SoupAttributes(5, 25, List.of(new EffectWithDuration(FalloutMcEffects.EXAMPLE_EFFECT.value(), 0)), List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 10, 15, 0.5, true, 12), false)
            .add(wrapItemAsHolder(Items.RABBIT_STEW), new SoupAttributes(5, 11, List.of(new EffectWithDuration(FalloutMcEffects.EXAMPLE_EFFECT.value(), 0)), List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 10, 15, 0.6, true, 7), false)
            .add(wrapItemAsHolder(Items.SUSPICIOUS_STEW), new SoupAttributes(5, 30, List.of(new EffectWithDuration(FalloutMcEffects.EXAMPLE_EFFECT.value(), 0)), List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 10, 15, 0.8, true, 25), false);

        this.builder(FalloutMcDataMaps.DRINK_ATTRIBUTES)
            .add(wrapItemAsHolder(Items.LINGERING_POTION), new DrinkAttributes(20, 0, 0, List.of(new EffectWithDuration(FalloutMcEffects.EXAMPLE_EFFECT.value(), 0)), List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 12, 1, 0, false, false), false)
            .add(wrapItemAsHolder(Items.POTION), new DrinkAttributes(20, 0, 0, List.of(new EffectWithDuration(FalloutMcEffects.EXAMPLE_EFFECT.value(), 0)), List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 12, 1, 0, false, false), false)
            .add(wrapItemAsHolder(Items.SPLASH_POTION), new DrinkAttributes(20, 0, 0, List.of(new EffectWithDuration(FalloutMcEffects.EXAMPLE_EFFECT.value(), 0)), List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 12, 1, 0, false, false), false)
            .add(wrapItemAsHolder(Items.OMINOUS_BOTTLE), new DrinkAttributes(20, 0, 0, List.of(new EffectWithDuration(FalloutMcEffects.EXAMPLE_EFFECT.value(), 0)), List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 12, 1, 0, false, false), false)
        ;
    }
}
