package dev.cassis2310.falloutmc.datagen;

import dev.cassis2310.falloutmc.datagen.codecs.items.Consumables.*;
import dev.cassis2310.falloutmc.datagen.datamaps.FalloutMcDataMaps;
import dev.cassis2310.falloutmc.effects.FalloutMcEffects;
import dev.cassis2310.falloutmc.items.FalloutMcItems;
import net.minecraft.core.HolderLookup;
import net.minecraft.data.PackOutput;
import net.minecraft.world.effect.MobEffect;
import net.minecraft.world.item.Items;
import net.neoforged.neoforge.common.data.DataMapProvider;

import java.util.List;
import java.util.concurrent.CompletableFuture;

import static dev.cassis2310.falloutmc.utils.helpers.ItemHelpers.wrapItemAsHolder;

/**
 * This class is responsible for providing data maps.
 * It extends the {@link DataMapProvider} class to gather and register all the relevant data.
 */
public class FalloutMcDataMapProvider extends DataMapProvider
{

    /**
     * Creates a new instance of {@code FalloutMcDataMapProvider}.
     *
     * @param packOutput     the output location where data maps will be saved
     * @param lookupProvider a {@link CompletableFuture} that supplies the registries needed for data generation
     */
    protected FalloutMcDataMapProvider(PackOutput packOutput, CompletableFuture<HolderLookup.Provider> lookupProvider)
    {
        super(packOutput, lookupProvider);
    }

    /**
     * Gathers data map entries related to item weights.
     * This method populates the data map with item IDs and their corresponding weights.
     * The weights are used for various purposes, such as inventory management in the game.
     *
     * <h3>Usage Examples:</h3>
     * <p>
     * <h4>Example 1 (Furnace fuels):</h4>
     * <pre>{@code
     * this.builder(NeoForgeDataMaps.FURNACE_FUELS)
     *         .add(FalloutMcItems.NUCLEAR_SCRAP.getId(), new FurnaceFuel(1200), false);
     * }</pre>
     * </p>
     */
    @Override
    protected void gather()
    {
        addCustomItems();
        addVanillaItems();
    }

    /**
     * Adds custom items to the data map with their corresponding weights.
     * This method populates the item weight data map with custom items specific to the Fallout MC mod.
     * <p>
     * This method doesn't return any value and is called internally during the data gathering process.
     */
    private void addCustomItems()
    {
        // Custom items
        this.builder(FalloutMcDataMaps.ITEM_ATTRIBUTES)
                .add(FalloutMcItems.NUKA_COLA.getId(), new ItemAttributes(1.0, 10), false);
    }

    /**
     * Adds vanilla Minecraft items to the data map with their corresponding weights.
     * This method populates the item weight data map with standard building blocks available in Minecraft.
     * <p>
     * This method doesn't return any value and is called internally during the data gathering process.
     */
    private void addVanillaItems()
    {
        this.builder(FalloutMcDataMaps.ITEM_ATTRIBUTES)
                // Building Blocks
                .add(wrapItemAsHolder(Items.OAK_LOG), new ItemAttributes(15.0, -1), false)
                .add(wrapItemAsHolder(Items.OAK_WOOD), new ItemAttributes(12.0, -1), false)
                .add(wrapItemAsHolder(Items.STRIPPED_OAK_LOG), new ItemAttributes(12.0, -1), false)
                .add(wrapItemAsHolder(Items.STRIPPED_OAK_WOOD), new ItemAttributes(11.0, -1), false)
                .add(wrapItemAsHolder(Items.OAK_PLANKS), new ItemAttributes(3.0, -1), false)
                .add(wrapItemAsHolder(Items.OAK_STAIRS), new ItemAttributes(5.0, -1), false)
                .add(wrapItemAsHolder(Items.OAK_SLAB), new ItemAttributes(1.5, -1), false)
                .add(wrapItemAsHolder(Items.OAK_FENCE), new ItemAttributes(4.0, -1), false)
                .add(wrapItemAsHolder(Items.OAK_FENCE_GATE), new ItemAttributes(5.0, -1), false)
                .add(wrapItemAsHolder(Items.OAK_DOOR), new ItemAttributes(8.0, -1), false)
                .add(wrapItemAsHolder(Items.OAK_TRAPDOOR), new ItemAttributes(4.0, -1), false)
                .add(wrapItemAsHolder(Items.OAK_PRESSURE_PLATE), new ItemAttributes(0.5, -1), false)
                .add(wrapItemAsHolder(Items.OAK_BUTTON), new ItemAttributes(0.1, -1), false)
                .add(wrapItemAsHolder(Items.OAK_SIGN), new ItemAttributes(1.0, -1), false)
                .add(wrapItemAsHolder(Items.SPRUCE_LOG), new ItemAttributes(14.0, -1), false)
                .add(wrapItemAsHolder(Items.SPRUCE_WOOD), new ItemAttributes(11.0, -1), false)
                .add(wrapItemAsHolder(Items.STRIPPED_SPRUCE_LOG), new ItemAttributes(12.0, -1), false)
                .add(wrapItemAsHolder(Items.STRIPPED_SPRUCE_WOOD), new ItemAttributes(10.0, -1), false)
                .add(wrapItemAsHolder(Items.SPRUCE_PLANKS), new ItemAttributes(2.8, -1), false)
                .add(wrapItemAsHolder(Items.SPRUCE_STAIRS), new ItemAttributes(4.5, -1), false)
                .add(wrapItemAsHolder(Items.SPRUCE_SLAB), new ItemAttributes(1.2, -1), false)
                .add(wrapItemAsHolder(Items.SPRUCE_FENCE), new ItemAttributes(3.5, -1), false)
                .add(wrapItemAsHolder(Items.SPRUCE_FENCE_GATE), new ItemAttributes(5.0, -1), false)
                .add(wrapItemAsHolder(Items.SPRUCE_DOOR), new ItemAttributes(7.5, -1), false)
                .add(wrapItemAsHolder(Items.SPRUCE_TRAPDOOR), new ItemAttributes(3.5, -1), false)
                .add(wrapItemAsHolder(Items.SPRUCE_PRESSURE_PLATE), new ItemAttributes(0.5, -1), false)
                .add(wrapItemAsHolder(Items.SPRUCE_BUTTON), new ItemAttributes(0.1, -1), false)
                .add(wrapItemAsHolder(Items.SPRUCE_SIGN), new ItemAttributes(1.0, -1), false)
                .add(wrapItemAsHolder(Items.BIRCH_LOG), new ItemAttributes(12.0, -1), false)
                .add(wrapItemAsHolder(Items.BIRCH_WOOD), new ItemAttributes(9.5, -1), false)
                .add(wrapItemAsHolder(Items.STRIPPED_BIRCH_LOG), new ItemAttributes(9.8, -1), false)
                .add(wrapItemAsHolder(Items.STRIPPED_BIRCH_WOOD), new ItemAttributes(8.0, -1), false)
                .add(wrapItemAsHolder(Items.BIRCH_PLANKS), new ItemAttributes(2.5, -1), false)
                .add(wrapItemAsHolder(Items.BIRCH_STAIRS), new ItemAttributes(4.0, -1), false)
                .add(wrapItemAsHolder(Items.BIRCH_SLAB), new ItemAttributes(0.8, -1), false)
                .add(wrapItemAsHolder(Items.BIRCH_FENCE), new ItemAttributes(2.5, -1), false)
                .add(wrapItemAsHolder(Items.BIRCH_FENCE_GATE), new ItemAttributes(4.0, -1), false)
                .add(wrapItemAsHolder(Items.BIRCH_DOOR), new ItemAttributes(6.0, -1), false)
                .add(wrapItemAsHolder(Items.BIRCH_TRAPDOOR), new ItemAttributes(3.0, -1), false)
                .add(wrapItemAsHolder(Items.BIRCH_PRESSURE_PLATE), new ItemAttributes(0.4, -1), false)
                .add(wrapItemAsHolder(Items.BIRCH_BUTTON), new ItemAttributes(0.1, -1), false)
                .add(wrapItemAsHolder(Items.BIRCH_SIGN), new ItemAttributes(1.0, -1), false)
                .add(wrapItemAsHolder(Items.JUNGLE_LOG), new ItemAttributes(13.0, -1), false)
                .add(wrapItemAsHolder(Items.JUNGLE_WOOD), new ItemAttributes(10.0, -1), false)
                .add(wrapItemAsHolder(Items.STRIPPED_JUNGLE_LOG), new ItemAttributes(11.0, -1), false)
                .add(wrapItemAsHolder(Items.STRIPPED_JUNGLE_WOOD), new ItemAttributes(9.0, -1), false)
                .add(wrapItemAsHolder(Items.JUNGLE_PLANKS), new ItemAttributes(2.6, -1), false)
                .add(wrapItemAsHolder(Items.JUNGLE_STAIRS), new ItemAttributes(4.5, -1), false)
                .add(wrapItemAsHolder(Items.JUNGLE_SLAB), new ItemAttributes(1.2, -1), false)
                .add(wrapItemAsHolder(Items.JUNGLE_FENCE), new ItemAttributes(3.0, -1), false)
                .add(wrapItemAsHolder(Items.JUNGLE_FENCE_GATE), new ItemAttributes(5.0, -1), false)
                .add(wrapItemAsHolder(Items.JUNGLE_DOOR), new ItemAttributes(7.5, -1), false)
                .add(wrapItemAsHolder(Items.JUNGLE_TRAPDOOR), new ItemAttributes(3.5, -1), false)
                .add(wrapItemAsHolder(Items.JUNGLE_PRESSURE_PLATE), new ItemAttributes(0.5, -1), false)
                .add(wrapItemAsHolder(Items.JUNGLE_BUTTON), new ItemAttributes(0.1, -1), false)
                .add(wrapItemAsHolder(Items.JUNGLE_SIGN), new ItemAttributes(1.0, -1), false)
                .add(wrapItemAsHolder(Items.ACACIA_LOG), new ItemAttributes(12.0, -1), false)
                .add(wrapItemAsHolder(Items.ACACIA_WOOD), new ItemAttributes(10.0, -1), false)
                .add(wrapItemAsHolder(Items.STRIPPED_ACACIA_LOG), new ItemAttributes(10.5, -1), false)
                .add(wrapItemAsHolder(Items.STRIPPED_ACACIA_WOOD), new ItemAttributes(9.0, -1), false)
                .add(wrapItemAsHolder(Items.ACACIA_PLANKS), new ItemAttributes(2.5, -1), false)
                .add(wrapItemAsHolder(Items.ACACIA_STAIRS), new ItemAttributes(4.0, -1), false)
                .add(wrapItemAsHolder(Items.ACACIA_SLAB), new ItemAttributes(1.0, -1), false)
                .add(wrapItemAsHolder(Items.ACACIA_FENCE), new ItemAttributes(3.0, -1), false)
                .add(wrapItemAsHolder(Items.ACACIA_FENCE_GATE), new ItemAttributes(4.5, -1), false)
                .add(wrapItemAsHolder(Items.ACACIA_DOOR), new ItemAttributes(7.0, -1), false)
                .add(wrapItemAsHolder(Items.ACACIA_TRAPDOOR), new ItemAttributes(3.5, -1), false)
                .add(wrapItemAsHolder(Items.ACACIA_PRESSURE_PLATE), new ItemAttributes(0.5, -1), false)
                .add(wrapItemAsHolder(Items.ACACIA_BUTTON), new ItemAttributes(0.1, -1), false)
                .add(wrapItemAsHolder(Items.ACACIA_SIGN), new ItemAttributes(1.0, -1), false)
                .add(wrapItemAsHolder(Items.DARK_OAK_LOG), new ItemAttributes(14.0, -1), false)
                .add(wrapItemAsHolder(Items.DARK_OAK_WOOD), new ItemAttributes(12.0, -1), false)
                .add(wrapItemAsHolder(Items.STRIPPED_DARK_OAK_LOG), new ItemAttributes(12.5, -1), false)
                .add(wrapItemAsHolder(Items.STRIPPED_DARK_OAK_WOOD), new ItemAttributes(11.0, -1), false)
                .add(wrapItemAsHolder(Items.DARK_OAK_PLANKS), new ItemAttributes(3.0, -1), false)
                .add(wrapItemAsHolder(Items.DARK_OAK_STAIRS), new ItemAttributes(5.0, -1), false)
                .add(wrapItemAsHolder(Items.DARK_OAK_SLAB), new ItemAttributes(1.5, -1), false)
                .add(wrapItemAsHolder(Items.DARK_OAK_FENCE), new ItemAttributes(3.5, -1), false)
                .add(wrapItemAsHolder(Items.DARK_OAK_FENCE_GATE), new ItemAttributes(5.5, -1), false)
                .add(wrapItemAsHolder(Items.DARK_OAK_DOOR), new ItemAttributes(8.0, -1), false)
                .add(wrapItemAsHolder(Items.DARK_OAK_TRAPDOOR), new ItemAttributes(4.0, -1), false)
                .add(wrapItemAsHolder(Items.DARK_OAK_PRESSURE_PLATE), new ItemAttributes(0.6, -1), false)
                .add(wrapItemAsHolder(Items.DARK_OAK_BUTTON), new ItemAttributes(0.1, -1), false)
                .add(wrapItemAsHolder(Items.DARK_OAK_SIGN), new ItemAttributes(1.0, -1), false)
                .add(wrapItemAsHolder(Items.MANGROVE_LOG), new ItemAttributes(15.0, -1), false)
                .add(wrapItemAsHolder(Items.MANGROVE_WOOD), new ItemAttributes(12.0, -1), false)
                .add(wrapItemAsHolder(Items.STRIPPED_MANGROVE_LOG), new ItemAttributes(13.0, -1), false)
                .add(wrapItemAsHolder(Items.STRIPPED_MANGROVE_WOOD), new ItemAttributes(10.5, -1), false)
                .add(wrapItemAsHolder(Items.MANGROVE_PLANKS), new ItemAttributes(3.5, -1), false)
                .add(wrapItemAsHolder(Items.MANGROVE_STAIRS), new ItemAttributes(5.5, -1), false)
                .add(wrapItemAsHolder(Items.MANGROVE_SLAB), new ItemAttributes(1.5, -1), false)
                .add(wrapItemAsHolder(Items.MANGROVE_FENCE), new ItemAttributes(4.0, -1), false)
                .add(wrapItemAsHolder(Items.MANGROVE_FENCE_GATE), new ItemAttributes(5.5, -1), false)
                .add(wrapItemAsHolder(Items.MANGROVE_DOOR), new ItemAttributes(8.0, -1), false)
                .add(wrapItemAsHolder(Items.MANGROVE_TRAPDOOR), new ItemAttributes(4.5, -1), false)
                .add(wrapItemAsHolder(Items.MANGROVE_PRESSURE_PLATE), new ItemAttributes(0.7, -1), false)
                .add(wrapItemAsHolder(Items.MANGROVE_BUTTON), new ItemAttributes(0.2, -1), false)
                .add(wrapItemAsHolder(Items.MANGROVE_SIGN), new ItemAttributes(1.5, -1), false)
                .add(wrapItemAsHolder(Items.CHERRY_LOG), new ItemAttributes(11.0, -1), false)
                .add(wrapItemAsHolder(Items.CHERRY_WOOD), new ItemAttributes(9.0, -1), false)
                .add(wrapItemAsHolder(Items.STRIPPED_CHERRY_LOG), new ItemAttributes(10.0, -1), false)
                .add(wrapItemAsHolder(Items.STRIPPED_CHERRY_WOOD), new ItemAttributes(8.0, -1), false)
                .add(wrapItemAsHolder(Items.CHERRY_PLANKS), new ItemAttributes(2.5, -1), false)
                .add(wrapItemAsHolder(Items.CHERRY_STAIRS), new ItemAttributes(4.0, -1), false)
                .add(wrapItemAsHolder(Items.CHERRY_SLAB), new ItemAttributes(1.0, -1), false)
                .add(wrapItemAsHolder(Items.CHERRY_FENCE), new ItemAttributes(3.0, -1), false)
                .add(wrapItemAsHolder(Items.CHERRY_FENCE_GATE), new ItemAttributes(4.5, -1), false)
                .add(wrapItemAsHolder(Items.CHERRY_DOOR), new ItemAttributes(7.0, -1), false)
                .add(wrapItemAsHolder(Items.CHERRY_TRAPDOOR), new ItemAttributes(3.5, -1), false)
                .add(wrapItemAsHolder(Items.CHERRY_PRESSURE_PLATE), new ItemAttributes(0.6, -1), false)
                .add(wrapItemAsHolder(Items.CHERRY_BUTTON), new ItemAttributes(0.2, -1), false)
                .add(wrapItemAsHolder(Items.CHERRY_SIGN), new ItemAttributes(1.2, -1), false)
                .add(wrapItemAsHolder(Items.BAMBOO_BLOCK), new ItemAttributes(6.0, -1), false)
                .add(wrapItemAsHolder(Items.STRIPPED_BAMBOO_BLOCK), new ItemAttributes(1.8, -1), false)
                .add(wrapItemAsHolder(Items.BAMBOO_PLANKS), new ItemAttributes(0.4, -1), false)
                .add(wrapItemAsHolder(Items.BAMBOO_MOSAIC), new ItemAttributes(0.5, -1), false)
                .add(wrapItemAsHolder(Items.BAMBOO_STAIRS), new ItemAttributes(0.5, -1), false)
                .add(wrapItemAsHolder(Items.BAMBOO_MOSAIC_STAIRS), new ItemAttributes(0.5, -1), false)
                .add(wrapItemAsHolder(Items.BAMBOO_SLAB), new ItemAttributes(0.4, -1), false)
                .add(wrapItemAsHolder(Items.BAMBOO_MOSAIC_SLAB), new ItemAttributes(0.4, -1), false)
                .add(wrapItemAsHolder(Items.BAMBOO_FENCE), new ItemAttributes(0.5, -1), false)
                .add(wrapItemAsHolder(Items.BAMBOO_FENCE_GATE), new ItemAttributes(0.5, -1), false)
                .add(wrapItemAsHolder(Items.BAMBOO_DOOR), new ItemAttributes(0.7, -1), false)
                .add(wrapItemAsHolder(Items.BAMBOO_TRAPDOOR), new ItemAttributes(0.5, -1), false)
                .add(wrapItemAsHolder(Items.BAMBOO_PRESSURE_PLATE), new ItemAttributes(0.4, -1), false)
                .add(wrapItemAsHolder(Items.BAMBOO_BUTTON), new ItemAttributes(0.1, -1), false)
                .add(wrapItemAsHolder(Items.BAMBOO_SIGN), new ItemAttributes(0.3, -1), false)
                .add(wrapItemAsHolder(Items.CRIMSON_STEM), new ItemAttributes(2.5, -1), false)
                .add(wrapItemAsHolder(Items.STRIPPED_CRIMSON_STEM), new ItemAttributes(1.8, -1), false)
                .add(wrapItemAsHolder(Items.CRIMSON_HYPHAE), new ItemAttributes(1.8, -1), false)
                .add(wrapItemAsHolder(Items.STRIPPED_CRIMSON_HYPHAE), new ItemAttributes(1.5, -1), false)
                .add(wrapItemAsHolder(Items.CRIMSON_PLANKS), new ItemAttributes(1.2, -1), false)
                .add(wrapItemAsHolder(Items.CRIMSON_STAIRS), new ItemAttributes(1.2, -1), false)
                .add(wrapItemAsHolder(Items.CRIMSON_SLAB), new ItemAttributes(0.9, -1), false)
                .add(wrapItemAsHolder(Items.CRIMSON_FENCE), new ItemAttributes(1.0, -1), false)
                .add(wrapItemAsHolder(Items.CRIMSON_FENCE_GATE), new ItemAttributes(1.2, -1), false)
                .add(wrapItemAsHolder(Items.CRIMSON_DOOR), new ItemAttributes(1.8, -1), false)
                .add(wrapItemAsHolder(Items.CRIMSON_TRAPDOOR), new ItemAttributes(1.2, -1), false)
                .add(wrapItemAsHolder(Items.CRIMSON_PRESSURE_PLATE), new ItemAttributes(0.7, -1), false)
                .add(wrapItemAsHolder(Items.CRIMSON_BUTTON), new ItemAttributes(0.1, -1), false)
                .add(wrapItemAsHolder(Items.CRIMSON_SIGN), new ItemAttributes(0.4, -1), false)
                .add(wrapItemAsHolder(Items.WARPED_STEM), new ItemAttributes(2.5, -1), false)
                .add(wrapItemAsHolder(Items.STRIPPED_WARPED_STEM), new ItemAttributes(1.8, -1), false)
                .add(wrapItemAsHolder(Items.WARPED_HYPHAE), new ItemAttributes(1.8, -1), false)
                .add(wrapItemAsHolder(Items.STRIPPED_WARPED_HYPHAE), new ItemAttributes(1.5, -1), false)
                .add(wrapItemAsHolder(Items.WARPED_PLANKS), new ItemAttributes(1.2, -1), false)
                .add(wrapItemAsHolder(Items.WARPED_STAIRS), new ItemAttributes(1.2, -1), false)
                .add(wrapItemAsHolder(Items.WARPED_SLAB), new ItemAttributes(0.9, -1), false)
                .add(wrapItemAsHolder(Items.WARPED_FENCE), new ItemAttributes(1.0, -1), false)
                .add(wrapItemAsHolder(Items.WARPED_FENCE_GATE), new ItemAttributes(1.2, -1), false)
                .add(wrapItemAsHolder(Items.WARPED_DOOR), new ItemAttributes(1.8, -1), false)
                .add(wrapItemAsHolder(Items.WARPED_TRAPDOOR), new ItemAttributes(1.2, -1), false)
                .add(wrapItemAsHolder(Items.WARPED_PRESSURE_PLATE), new ItemAttributes(0.7, -1), false)
                .add(wrapItemAsHolder(Items.WARPED_BUTTON), new ItemAttributes(0.1, -1), false)
                .add(wrapItemAsHolder(Items.WARPED_SIGN), new ItemAttributes(0.4, -1), false)
                .add(wrapItemAsHolder(Items.STONE), new ItemAttributes(5.5, -1), false)
                .add(wrapItemAsHolder(Items.STONE_STAIRS), new ItemAttributes(4.5, -1), false)
                .add(wrapItemAsHolder(Items.STONE_SLAB), new ItemAttributes(3.0, -1), false)
                .add(wrapItemAsHolder(Items.STONE_PRESSURE_PLATE), new ItemAttributes(2.0, -1), false)
                .add(wrapItemAsHolder(Items.STONE_BUTTON), new ItemAttributes(0.5, -1), false)
                .add(wrapItemAsHolder(Items.COBBLESTONE), new ItemAttributes(5.0, -1), false)
                .add(wrapItemAsHolder(Items.COBBLESTONE_STAIRS), new ItemAttributes(4.0, -1), false)
                .add(wrapItemAsHolder(Items.COBBLESTONE_SLAB), new ItemAttributes(3.0, -1), false)
                .add(wrapItemAsHolder(Items.COBBLESTONE_WALL), new ItemAttributes(5.0, -1), false)
                .add(wrapItemAsHolder(Items.MOSSY_COBBLESTONE), new ItemAttributes(5.0, -1), false)
                .add(wrapItemAsHolder(Items.MOSSY_COBBLESTONE_STAIRS), new ItemAttributes(4.0, -1), false)
                .add(wrapItemAsHolder(Items.MOSSY_COBBLESTONE_SLAB), new ItemAttributes(2.5, -1), false)
                .add(wrapItemAsHolder(Items.MOSSY_COBBLESTONE_WALL), new ItemAttributes(5.0, -1), false)
                .add(wrapItemAsHolder(Items.SMOOTH_STONE), new ItemAttributes(5.0, -1), false)
                .add(wrapItemAsHolder(Items.SMOOTH_STONE_SLAB), new ItemAttributes(3.5, -1), false)
                .add(wrapItemAsHolder(Items.STONE_BRICKS), new ItemAttributes(6.0, -1), false)
                .add(wrapItemAsHolder(Items.CRACKED_STONE_BRICKS), new ItemAttributes(5.5, -1), false)
                .add(wrapItemAsHolder(Items.STONE_BRICK_STAIRS), new ItemAttributes(5.0, -1), false)
                .add(wrapItemAsHolder(Items.STONE_BRICK_SLAB), new ItemAttributes(4.0, -1), false)
                .add(wrapItemAsHolder(Items.STONE_BRICK_WALL), new ItemAttributes(6.0, -1), false)
                .add(wrapItemAsHolder(Items.CHISELED_STONE_BRICKS), new ItemAttributes(6.0, -1), false)
                .add(wrapItemAsHolder(Items.MOSSY_STONE_BRICKS), new ItemAttributes(6.0, -1), false)
                .add(wrapItemAsHolder(Items.MOSSY_STONE_BRICK_STAIRS), new ItemAttributes(5.0, -1), false)
                .add(wrapItemAsHolder(Items.MOSSY_STONE_BRICK_SLAB), new ItemAttributes(3.5, -1), false)
                .add(wrapItemAsHolder(Items.MOSSY_STONE_BRICK_WALL), new ItemAttributes(6.0, -1), false)
                .add(wrapItemAsHolder(Items.GRANITE), new ItemAttributes(6.5, -1), false)
                .add(wrapItemAsHolder(Items.GRANITE_STAIRS), new ItemAttributes(5.5, -1), false)
                .add(wrapItemAsHolder(Items.GRANITE_SLAB), new ItemAttributes(4.5, -1), false)
                .add(wrapItemAsHolder(Items.GRANITE_WALL), new ItemAttributes(6.5, -1), false)
                .add(wrapItemAsHolder(Items.POLISHED_GRANITE), new ItemAttributes(6.5, -1), false)
                .add(wrapItemAsHolder(Items.POLISHED_GRANITE_STAIRS), new ItemAttributes(5.5, -1), false)
                .add(wrapItemAsHolder(Items.POLISHED_GRANITE_SLAB), new ItemAttributes(4.5, -1), false)
                .add(wrapItemAsHolder(Items.DIORITE), new ItemAttributes(6.5, -1), false)
                .add(wrapItemAsHolder(Items.DIORITE_STAIRS), new ItemAttributes(5.5, -1), false)
                .add(wrapItemAsHolder(Items.DIORITE_SLAB), new ItemAttributes(4.5, -1), false)
                .add(wrapItemAsHolder(Items.DIORITE_WALL), new ItemAttributes(6.5, -1), false)
                .add(wrapItemAsHolder(Items.POLISHED_DIORITE), new ItemAttributes(6.5, -1), false)
                .add(wrapItemAsHolder(Items.POLISHED_DIORITE_STAIRS), new ItemAttributes(5.5, -1), false)
                .add(wrapItemAsHolder(Items.POLISHED_DIORITE_SLAB), new ItemAttributes(4.5, -1), false)
                .add(wrapItemAsHolder(Items.ANDESITE), new ItemAttributes(7.0, -1), false)
                .add(wrapItemAsHolder(Items.ANDESITE_STAIRS), new ItemAttributes(6.0, -1), false)
                .add(wrapItemAsHolder(Items.ANDESITE_SLAB), new ItemAttributes(5.0, -1), false)
                .add(wrapItemAsHolder(Items.ANDESITE_WALL), new ItemAttributes(7.0, -1), false)
                .add(wrapItemAsHolder(Items.POLISHED_ANDESITE), new ItemAttributes(7.0, -1), false)
                .add(wrapItemAsHolder(Items.POLISHED_ANDESITE_STAIRS), new ItemAttributes(6.0, -1), false)
                .add(wrapItemAsHolder(Items.POLISHED_ANDESITE_SLAB), new ItemAttributes(5.0, -1), false)
                .add(wrapItemAsHolder(Items.DEEPSLATE), new ItemAttributes(9.0, -1), false)
                .add(wrapItemAsHolder(Items.COBBLED_DEEPSLATE), new ItemAttributes(8.0, -1), false)
                .add(wrapItemAsHolder(Items.COBBLED_DEEPSLATE_STAIRS), new ItemAttributes(7.0, -1), false)
                .add(wrapItemAsHolder(Items.COBBLED_DEEPSLATE_SLAB), new ItemAttributes(6.0, -1), false)
                .add(wrapItemAsHolder(Items.COBBLED_DEEPSLATE_WALL), new ItemAttributes(8.0, -1), false)
                .add(wrapItemAsHolder(Items.CHISELED_DEEPSLATE), new ItemAttributes(9.0, -1), false)
                .add(wrapItemAsHolder(Items.POLISHED_DEEPSLATE), new ItemAttributes(8.0, -1), false)
                .add(wrapItemAsHolder(Items.POLISHED_DEEPSLATE_STAIRS), new ItemAttributes(7.0, -1), false)
                .add(wrapItemAsHolder(Items.POLISHED_DEEPSLATE_SLAB), new ItemAttributes(6.0, -1), false)
                .add(wrapItemAsHolder(Items.POLISHED_DEEPSLATE_WALL), new ItemAttributes(8.0, -1), false)
                .add(wrapItemAsHolder(Items.DEEPSLATE_BRICKS), new ItemAttributes(9.0, -1), false)
                .add(wrapItemAsHolder(Items.CRACKED_DEEPSLATE_BRICKS), new ItemAttributes(9.0, -1), false)
                .add(wrapItemAsHolder(Items.DEEPSLATE_BRICK_STAIRS), new ItemAttributes(7.0, -1), false)
                .add(wrapItemAsHolder(Items.DEEPSLATE_BRICK_SLAB), new ItemAttributes(8.0, -1), false)
                .add(wrapItemAsHolder(Items.DEEPSLATE_BRICK_WALL), new ItemAttributes(9.0, -1), false)
                .add(wrapItemAsHolder(Items.DEEPSLATE_TILES), new ItemAttributes(9.0, -1), false)
                .add(wrapItemAsHolder(Items.CRACKED_DEEPSLATE_TILES), new ItemAttributes(9.0, -1), false)
                .add(wrapItemAsHolder(Items.DEEPSLATE_TILE_STAIRS), new ItemAttributes(7.0, -1), false)
                .add(wrapItemAsHolder(Items.DEEPSLATE_TILE_SLAB), new ItemAttributes(8.0, -1), false)
                .add(wrapItemAsHolder(Items.DEEPSLATE_TILE_WALL), new ItemAttributes(9.0, -1), false)
                .add(wrapItemAsHolder(Items.REINFORCED_DEEPSLATE), new ItemAttributes(8.0, -1), false)
                .add(wrapItemAsHolder(Items.TUFF), new ItemAttributes(5.0, -1), false)
                .add(wrapItemAsHolder(Items.TUFF_STAIRS), new ItemAttributes(6.5, -1), false)
                .add(wrapItemAsHolder(Items.TUFF_SLAB), new ItemAttributes(4.5, -1), false)
                .add(wrapItemAsHolder(Items.TUFF_WALL), new ItemAttributes(7.0, -1), false)
                .add(wrapItemAsHolder(Items.CHISELED_TUFF), new ItemAttributes(6.0, -1), false)
                .add(wrapItemAsHolder(Items.POLISHED_TUFF), new ItemAttributes(5.5, -1), false)
                .add(wrapItemAsHolder(Items.POLISHED_TUFF_STAIRS), new ItemAttributes(6.5, -1), false)
                .add(wrapItemAsHolder(Items.POLISHED_TUFF_SLAB), new ItemAttributes(4.5, -1), false)
                .add(wrapItemAsHolder(Items.POLISHED_TUFF_WALL), new ItemAttributes(7.0, -1), false)
                .add(wrapItemAsHolder(Items.TUFF_BRICKS), new ItemAttributes(5.0, -1), false)
                .add(wrapItemAsHolder(Items.TUFF_BRICK_STAIRS), new ItemAttributes(6.0, -1), false)
                .add(wrapItemAsHolder(Items.TUFF_BRICK_SLAB), new ItemAttributes(4.0, -1), false)
                .add(wrapItemAsHolder(Items.TUFF_BRICK_WALL), new ItemAttributes(6.5, -1), false)
                .add(wrapItemAsHolder(Items.CHISELED_TUFF_BRICKS), new ItemAttributes(5.5, -1), false)
                .add(wrapItemAsHolder(Items.BRICKS), new ItemAttributes(4.0, -1), false)
                .add(wrapItemAsHolder(Items.BRICK_STAIRS), new ItemAttributes(5.5, -1), false)
                .add(wrapItemAsHolder(Items.BRICK_SLAB), new ItemAttributes(3.5, -1), false)
                .add(wrapItemAsHolder(Items.BRICK_WALL), new ItemAttributes(6.0, -1), false)
                .add(wrapItemAsHolder(Items.PACKED_MUD), new ItemAttributes(3.0, -1), false)
                .add(wrapItemAsHolder(Items.MUD_BRICKS), new ItemAttributes(4.0, -1), false)
                .add(wrapItemAsHolder(Items.MUD_BRICK_STAIRS), new ItemAttributes(5.0, -1), false)
                .add(wrapItemAsHolder(Items.MUD_BRICK_SLAB), new ItemAttributes(3.5, -1), false)
                .add(wrapItemAsHolder(Items.MUD_BRICK_WALL), new ItemAttributes(5.5, -1), false)
                .add(wrapItemAsHolder(Items.SANDSTONE), new ItemAttributes(3.0, -1), false)
                .add(wrapItemAsHolder(Items.SANDSTONE_STAIRS), new ItemAttributes(5.0, -1), false)
                .add(wrapItemAsHolder(Items.SANDSTONE_SLAB), new ItemAttributes(3.5, -1), false)
                .add(wrapItemAsHolder(Items.SANDSTONE_WALL), new ItemAttributes(5.0, -1), false)
                .add(wrapItemAsHolder(Items.CHISELED_SANDSTONE), new ItemAttributes(4.0, -1), false)
                .add(wrapItemAsHolder(Items.SMOOTH_SANDSTONE), new ItemAttributes(3.5, -1), false)
                .add(wrapItemAsHolder(Items.SMOOTH_SANDSTONE_STAIRS), new ItemAttributes(5.0, -1), false)
                .add(wrapItemAsHolder(Items.SMOOTH_SANDSTONE_SLAB), new ItemAttributes(3.5, -1), false)
                .add(wrapItemAsHolder(Items.CUT_SANDSTONE), new ItemAttributes(5.0, -1), false)
                .add(wrapItemAsHolder(Items.CUT_STANDSTONE_SLAB), new ItemAttributes(4.5, -1), false)
                .add(wrapItemAsHolder(Items.RED_SANDSTONE), new ItemAttributes(3.0, -1), false)
                .add(wrapItemAsHolder(Items.RED_SANDSTONE_STAIRS), new ItemAttributes(5.0, -1), false)
                .add(wrapItemAsHolder(Items.RED_SANDSTONE_SLAB), new ItemAttributes(3.5, -1), false)
                .add(wrapItemAsHolder(Items.RED_SANDSTONE_WALL), new ItemAttributes(5.0, -1), false)
                .add(wrapItemAsHolder(Items.CHISELED_RED_SANDSTONE), new ItemAttributes(4.0, -1), false)
                .add(wrapItemAsHolder(Items.SMOOTH_RED_SANDSTONE), new ItemAttributes(3.5, -1), false)
                .add(wrapItemAsHolder(Items.SMOOTH_RED_SANDSTONE_STAIRS), new ItemAttributes(5.0, -1), false)
                .add(wrapItemAsHolder(Items.SMOOTH_RED_SANDSTONE_SLAB), new ItemAttributes(3.5, -1), false)
                .add(wrapItemAsHolder(Items.CUT_RED_SANDSTONE), new ItemAttributes(5.0, -1), false)
                .add(wrapItemAsHolder(Items.CUT_RED_SANDSTONE_SLAB), new ItemAttributes(4.5, -1), false)
                .add(wrapItemAsHolder(Items.SEA_LANTERN), new ItemAttributes(1.5, -1), false)
                .add(wrapItemAsHolder(Items.PRISMARINE), new ItemAttributes(3.0, -1), false)
                .add(wrapItemAsHolder(Items.PRISMARINE_STAIRS), new ItemAttributes(5.0, -1), false)
                .add(wrapItemAsHolder(Items.PRISMARINE_SLAB), new ItemAttributes(4.0, -1), false)
                .add(wrapItemAsHolder(Items.PRISMARINE_WALL), new ItemAttributes(6.0, -1), false)
                .add(wrapItemAsHolder(Items.PRISMARINE_BRICKS), new ItemAttributes(3.0, -1), false)
                .add(wrapItemAsHolder(Items.PRISMARINE_BRICK_STAIRS), new ItemAttributes(5.0, -1), false)
                .add(wrapItemAsHolder(Items.PRISMARINE_BRICK_SLAB), new ItemAttributes(4.0, -1), false)
                .add(wrapItemAsHolder(Items.DARK_PRISMARINE), new ItemAttributes(4.0, -1), false)
                .add(wrapItemAsHolder(Items.DARK_PRISMARINE_STAIRS), new ItemAttributes(6.0, -1), false)
                .add(wrapItemAsHolder(Items.DARK_PRISMARINE_SLAB), new ItemAttributes(5.0, -1), false)
                .add(wrapItemAsHolder(Items.NETHERRACK), new ItemAttributes(3.0, -1), false)
                .add(wrapItemAsHolder(Items.NETHER_BRICKS), new ItemAttributes(4.0, -1), false)
                .add(wrapItemAsHolder(Items.CRACKED_NETHER_BRICKS), new ItemAttributes(4.0, -1), false)
                .add(wrapItemAsHolder(Items.NETHER_BRICK_STAIRS), new ItemAttributes(5.0, -1), false)
                .add(wrapItemAsHolder(Items.NETHER_BRICK_SLAB), new ItemAttributes(3.5, -1), false)
                .add(wrapItemAsHolder(Items.NETHER_BRICK_WALL), new ItemAttributes(6.0, -1), false)
                .add(wrapItemAsHolder(Items.NETHER_BRICK_FENCE), new ItemAttributes(5.0, -1), false)
                .add(wrapItemAsHolder(Items.CHISELED_NETHER_BRICKS), new ItemAttributes(4.5, -1), false)
                .add(wrapItemAsHolder(Items.RED_NETHER_BRICKS), new ItemAttributes(4.0, -1), false)
                .add(wrapItemAsHolder(Items.RED_NETHER_BRICK_STAIRS), new ItemAttributes(5.0, -1), false)
                .add(wrapItemAsHolder(Items.RED_NETHER_BRICK_SLAB), new ItemAttributes(3.5, -1), false)
                .add(wrapItemAsHolder(Items.RED_NETHER_BRICK_WALL), new ItemAttributes(6.0, -1), false)
                .add(wrapItemAsHolder(Items.BASALT), new ItemAttributes(5.0, -1), false)
                .add(wrapItemAsHolder(Items.SMOOTH_BASALT), new ItemAttributes(5.5, -1), false)
                .add(wrapItemAsHolder(Items.POLISHED_BASALT), new ItemAttributes(6.0, -1), false)
                .add(wrapItemAsHolder(Items.BLACKSTONE), new ItemAttributes(5.0, -1), false)
                .add(wrapItemAsHolder(Items.BLACKSTONE), new ItemAttributes(5.0, -1), false)
                .add(wrapItemAsHolder(Items.GILDED_BLACKSTONE), new ItemAttributes(6.0, -1), false)
                .add(wrapItemAsHolder(Items.BLACKSTONE_STAIRS), new ItemAttributes(6.0, -1), false)
                .add(wrapItemAsHolder(Items.BLACKSTONE_SLAB), new ItemAttributes(4.5, -1), false)
                .add(wrapItemAsHolder(Items.BLACKSTONE_WALL), new ItemAttributes(6.0, -1), false)
                .add(wrapItemAsHolder(Items.CHISELED_POLISHED_BLACKSTONE), new ItemAttributes(6.0, -1), false)
                .add(wrapItemAsHolder(Items.POLISHED_BLACKSTONE), new ItemAttributes(6.0, -1), false)
                .add(wrapItemAsHolder(Items.POLISHED_BLACKSTONE_STAIRS), new ItemAttributes(6.0, -1), false)
                .add(wrapItemAsHolder(Items.POLISHED_BLACKSTONE_SLAB), new ItemAttributes(5.0, -1), false)
                .add(wrapItemAsHolder(Items.POLISHED_BLACKSTONE_WALL), new ItemAttributes(6.0, -1), false)
                .add(wrapItemAsHolder(Items.POLISHED_BLACKSTONE_PRESSURE_PLATE), new ItemAttributes(4.0, -1), false)
                .add(wrapItemAsHolder(Items.POLISHED_BLACKSTONE_BUTTON), new ItemAttributes(3.0, -1), false)
                .add(wrapItemAsHolder(Items.POLISHED_BLACKSTONE_BRICKS), new ItemAttributes(6.0, -1), false)
                .add(wrapItemAsHolder(Items.CRACKED_POLISHED_BLACKSTONE_BRICKS), new ItemAttributes(6.0, -1), false)
                .add(wrapItemAsHolder(Items.POLISHED_BLACKSTONE_BRICK_STAIRS), new ItemAttributes(6.0, -1), false)
                .add(wrapItemAsHolder(Items.POLISHED_BLACKSTONE_BRICK_SLAB), new ItemAttributes(5.0, -1), false)
                .add(wrapItemAsHolder(Items.POLISHED_BLACKSTONE_BRICK_WALL), new ItemAttributes(6.0, -1), false)
                .add(wrapItemAsHolder(Items.END_STONE), new ItemAttributes(4.5, -1), false)
                .add(wrapItemAsHolder(Items.END_STONE_BRICKS), new ItemAttributes(5.0, -1), false)
                .add(wrapItemAsHolder(Items.END_STONE_BRICK_STAIRS), new ItemAttributes(5.5, -1), false)
                .add(wrapItemAsHolder(Items.END_STONE_BRICK_SLAB), new ItemAttributes(4.0, -1), false)
                .add(wrapItemAsHolder(Items.END_STONE_BRICK_WALL), new ItemAttributes(5.5, -1), false)
                .add(wrapItemAsHolder(Items.PURPUR_BLOCK), new ItemAttributes(5.0, -1), false)
                .add(wrapItemAsHolder(Items.PURPUR_PILLAR), new ItemAttributes(5.0, -1), false)
                .add(wrapItemAsHolder(Items.PURPUR_STAIRS), new ItemAttributes(5.5, -1), false)
                .add(wrapItemAsHolder(Items.PURPUR_SLAB), new ItemAttributes(4.0, -1), false)
                .add(wrapItemAsHolder(Items.COAL_BLOCK), new ItemAttributes(6.0, -1), false)
                .add(wrapItemAsHolder(Items.IRON_BLOCK), new ItemAttributes(7.0, -1), false)
                .add(wrapItemAsHolder(Items.IRON_BARS), new ItemAttributes(3.5, -1), false)
                .add(wrapItemAsHolder(Items.IRON_DOOR), new ItemAttributes(6.0, -1), false)
                .add(wrapItemAsHolder(Items.IRON_TRAPDOOR), new ItemAttributes(5.5, -1), false)
                .add(wrapItemAsHolder(Items.HEAVY_WEIGHTED_PRESSURE_PLATE), new ItemAttributes(4.5, -1), false)
                .add(wrapItemAsHolder(Items.CHAIN), new ItemAttributes(2.5, -1), false)
                .add(wrapItemAsHolder(Items.GOLD_BLOCK), new ItemAttributes(30.0, -1), false)
                .add(wrapItemAsHolder(Items.LIGHT_WEIGHTED_PRESSURE_PLATE), new ItemAttributes(5.0, -1), false)
                .add(wrapItemAsHolder(Items.REDSTONE_BLOCK), new ItemAttributes(8.0, -1), false)
                .add(wrapItemAsHolder(Items.EMERALD_BLOCK), new ItemAttributes(7.0, -1), false)
                .add(wrapItemAsHolder(Items.LAPIS_BLOCK), new ItemAttributes(6.0, -1), false)
                .add(wrapItemAsHolder(Items.DIAMOND_BLOCK), new ItemAttributes(10.0, -1), false)
                .add(wrapItemAsHolder(Items.NETHERITE_BLOCK), new ItemAttributes(15.0, -1), false)
                .add(wrapItemAsHolder(Items.QUARTZ_BLOCK), new ItemAttributes(4.5, -1), false)
                .add(wrapItemAsHolder(Items.QUARTZ_STAIRS), new ItemAttributes(4.0, -1), false)
                .add(wrapItemAsHolder(Items.QUARTZ_SLAB), new ItemAttributes(3.5, -1), false)
                .add(wrapItemAsHolder(Items.CHISELED_QUARTZ_BLOCK), new ItemAttributes(5.0, -1), false)
                .add(wrapItemAsHolder(Items.QUARTZ_BRICKS), new ItemAttributes(4.5, -1), false)
                .add(wrapItemAsHolder(Items.QUARTZ_PILLAR), new ItemAttributes(5.5, -1), false)
                .add(wrapItemAsHolder(Items.SMOOTH_QUARTZ), new ItemAttributes(5.0, -1), false)
                .add(wrapItemAsHolder(Items.SMOOTH_QUARTZ_STAIRS), new ItemAttributes(4.5, -1), false)
                .add(wrapItemAsHolder(Items.SMOOTH_QUARTZ_SLAB), new ItemAttributes(3.0, -1), false)
                .add(wrapItemAsHolder(Items.AMETHYST_BLOCK), new ItemAttributes(6.0, -1), false)
                .add(wrapItemAsHolder(Items.COPPER_BLOCK), new ItemAttributes(5.0, -1), false)
                .add(wrapItemAsHolder(Items.CHISELED_COPPER), new ItemAttributes(4.0, -1), false)
                .add(wrapItemAsHolder(Items.COPPER_GRATE), new ItemAttributes(3.5, -1), false)
                .add(wrapItemAsHolder(Items.CUT_COPPER), new ItemAttributes(5.0, -1), false)
                .add(wrapItemAsHolder(Items.CUT_COPPER_STAIRS), new ItemAttributes(4.5, -1), false)
                .add(wrapItemAsHolder(Items.CUT_COPPER_SLAB), new ItemAttributes(3.5, -1), false)
                .add(wrapItemAsHolder(Items.COPPER_DOOR), new ItemAttributes(5.0, -1), false)
                .add(wrapItemAsHolder(Items.COPPER_TRAPDOOR), new ItemAttributes(4.0, -1), false)
                .add(wrapItemAsHolder(Items.COPPER_BULB), new ItemAttributes(2.0, -1), false)
                .add(wrapItemAsHolder(Items.EXPOSED_COPPER), new ItemAttributes(5.0, -1), false)
                .add(wrapItemAsHolder(Items.EXPOSED_CHISELED_COPPER), new ItemAttributes(4.0, -1), false)
                .add(wrapItemAsHolder(Items.EXPOSED_COPPER_GRATE), new ItemAttributes(3.5, -1), false)
                .add(wrapItemAsHolder(Items.EXPOSED_CUT_COPPER), new ItemAttributes(5.0, -1), false)
                .add(wrapItemAsHolder(Items.EXPOSED_CUT_COPPER_STAIRS), new ItemAttributes(4.5, -1), false)
                .add(wrapItemAsHolder(Items.EXPOSED_CUT_COPPER_SLAB), new ItemAttributes(3.0, -1), false)
                .add(wrapItemAsHolder(Items.EXPOSED_COPPER_DOOR), new ItemAttributes(5.0, -1), false)
                .add(wrapItemAsHolder(Items.EXPOSED_COPPER_TRAPDOOR), new ItemAttributes(4.0, -1), false)
                .add(wrapItemAsHolder(Items.EXPOSED_COPPER_BULB), new ItemAttributes(2.0, -1), false)
                .add(wrapItemAsHolder(Items.WEATHERED_COPPER), new ItemAttributes(7.0, -1), false)
                .add(wrapItemAsHolder(Items.WEATHERED_CHISELED_COPPER), new ItemAttributes(6.0, -1), false)
                .add(wrapItemAsHolder(Items.WEATHERED_COPPER_GRATE), new ItemAttributes(5.0, -1), false)
                .add(wrapItemAsHolder(Items.WEATHERED_CUT_COPPER), new ItemAttributes(7.0, -1), false)
                .add(wrapItemAsHolder(Items.WEATHERED_CUT_COPPER_STAIRS), new ItemAttributes(6.0, -1), false)
                .add(wrapItemAsHolder(Items.WEATHERED_CUT_COPPER_SLAB), new ItemAttributes(4.0, -1), false)
                .add(wrapItemAsHolder(Items.WEATHERED_COPPER_DOOR), new ItemAttributes(7.0, -1), false)
                .add(wrapItemAsHolder(Items.WEATHERED_COPPER_TRAPDOOR), new ItemAttributes(6.0, -1), false)
                .add(wrapItemAsHolder(Items.WEATHERED_COPPER_BULB), new ItemAttributes(2.5, -1), false)
                .add(wrapItemAsHolder(Items.OXIDIZED_COPPER), new ItemAttributes(7.0, -1), false)
                .add(wrapItemAsHolder(Items.OXIDIZED_CHISELED_COPPER), new ItemAttributes(6.0, -1), false)
                .add(wrapItemAsHolder(Items.OXIDIZED_COPPER_GRATE), new ItemAttributes(5.0, -1), false)
                .add(wrapItemAsHolder(Items.OXIDIZED_CUT_COPPER), new ItemAttributes(7.0, -1), false)
                .add(wrapItemAsHolder(Items.OXIDIZED_CUT_COPPER_STAIRS), new ItemAttributes(6.0, -1), false)
                .add(wrapItemAsHolder(Items.OXIDIZED_CUT_COPPER_SLAB), new ItemAttributes(4.5, -1), false)
                .add(wrapItemAsHolder(Items.OXIDIZED_COPPER_DOOR), new ItemAttributes(7.0, -1), false)
                .add(wrapItemAsHolder(Items.OXIDIZED_COPPER_TRAPDOOR), new ItemAttributes(6.0, -1), false)
                .add(wrapItemAsHolder(Items.OXIDIZED_COPPER_BULB), new ItemAttributes(2.5, -1), false)
                .add(wrapItemAsHolder(Items.WAXED_COPPER_BLOCK), new ItemAttributes(4.5, -1), false)
                .add(wrapItemAsHolder(Items.WAXED_CHISELED_COPPER), new ItemAttributes(3.5, -1), false)
                .add(wrapItemAsHolder(Items.WAXED_COPPER_GRATE), new ItemAttributes(3.0, -1), false)
                .add(wrapItemAsHolder(Items.WAXED_CUT_COPPER), new ItemAttributes(4.5, -1), false)
                .add(wrapItemAsHolder(Items.WAXED_CUT_COPPER_STAIRS), new ItemAttributes(3.5, -1), false)
                .add(wrapItemAsHolder(Items.WAXED_CUT_COPPER_SLAB), new ItemAttributes(3.0, -1), false)
                .add(wrapItemAsHolder(Items.WAXED_COPPER_DOOR), new ItemAttributes(4.5, -1), false)
                .add(wrapItemAsHolder(Items.WAXED_COPPER_TRAPDOOR), new ItemAttributes(3.5, -1), false)
                .add(wrapItemAsHolder(Items.WAXED_COPPER_BULB), new ItemAttributes(2.5, -1), false)
                .add(wrapItemAsHolder(Items.WAXED_EXPOSED_COPPER), new ItemAttributes(5.5, -1), false)
                .add(wrapItemAsHolder(Items.WAXED_EXPOSED_CHISELED_COPPER), new ItemAttributes(4.5, -1), false)
                .add(wrapItemAsHolder(Items.WAXED_EXPOSED_COPPER_GRATE), new ItemAttributes(3.5, -1), false)
                .add(wrapItemAsHolder(Items.WAXED_EXPOSED_CUT_COPPER), new ItemAttributes(5.5, -1), false)
                .add(wrapItemAsHolder(Items.WAXED_EXPOSED_CUT_COPPER_STAIRS), new ItemAttributes(4.5, -1), false)
                .add(wrapItemAsHolder(Items.WAXED_EXPOSED_CUT_COPPER_SLAB), new ItemAttributes(3.5, -1), false)
                .add(wrapItemAsHolder(Items.WAXED_EXPOSED_COPPER_DOOR), new ItemAttributes(5.5, -1), false)
                .add(wrapItemAsHolder(Items.WAXED_EXPOSED_COPPER_TRAPDOOR), new ItemAttributes(4.5, -1), false)
                .add(wrapItemAsHolder(Items.WAXED_EXPOSED_COPPER_BULB), new ItemAttributes(2.5, -1), false)
                .add(wrapItemAsHolder(Items.WAXED_WEATHERED_COPPER), new ItemAttributes(6.0, -1), false)
                .add(wrapItemAsHolder(Items.WAXED_WEATHERED_CHISELED_COPPER), new ItemAttributes(5.0, -1), false)
                .add(wrapItemAsHolder(Items.WAXED_WEATHERED_COPPER_GRATE), new ItemAttributes(4.0, -1), false)
                .add(wrapItemAsHolder(Items.WAXED_WEATHERED_CUT_COPPER), new ItemAttributes(6.0, -1), false)
                .add(wrapItemAsHolder(Items.WAXED_WEATHERED_CUT_COPPER_STAIRS), new ItemAttributes(5.0, -1), false)
                .add(wrapItemAsHolder(Items.WAXED_WEATHERED_CUT_COPPER_SLAB), new ItemAttributes(3.5, -1), false)
                .add(wrapItemAsHolder(Items.WAXED_WEATHERED_COPPER_DOOR), new ItemAttributes(6.0, -1), false)
                .add(wrapItemAsHolder(Items.WAXED_WEATHERED_COPPER_TRAPDOOR), new ItemAttributes(5.0, -1), false)
                .add(wrapItemAsHolder(Items.WAXED_WEATHERED_COPPER_BULB), new ItemAttributes(2.5, -1), false)
                .add(wrapItemAsHolder(Items.WAXED_OXIDIZED_COPPER), new ItemAttributes(7.0, -1), false)
                .add(wrapItemAsHolder(Items.WAXED_OXIDIZED_CHISELED_COPPER), new ItemAttributes(6.0, -1), false)
                .add(wrapItemAsHolder(Items.WAXED_OXIDIZED_COPPER_GRATE), new ItemAttributes(5.0, -1), false)
                .add(wrapItemAsHolder(Items.WAXED_OXIDIZED_CUT_COPPER), new ItemAttributes(7.0, -1), false)
                .add(wrapItemAsHolder(Items.WAXED_OXIDIZED_CUT_COPPER_STAIRS), new ItemAttributes(6.0, -1), false)
                .add(wrapItemAsHolder(Items.WAXED_OXIDIZED_CUT_COPPER_SLAB), new ItemAttributes(4.5, -1), false)
                .add(wrapItemAsHolder(Items.WAXED_OXIDIZED_COPPER_DOOR), new ItemAttributes(7.0, -1), false)
                .add(wrapItemAsHolder(Items.WAXED_OXIDIZED_COPPER_TRAPDOOR), new ItemAttributes(6.0, -1), false)
                .add(wrapItemAsHolder(Items.WAXED_OXIDIZED_COPPER_BULB), new ItemAttributes(2.5, -1), false);


        // Food & drinks
        this.builder(FalloutMcDataMaps.FOOD_ATTRIBUTES)
                .add(wrapItemAsHolder(Items.APPLE), new FoodAttributes(10, 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 0, 0, 0.2, false, false, false, 0), false)
                .add(wrapItemAsHolder(Items.BAKED_POTATO), new FoodAttributes(10, 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()),0, 0, 0, 0.4, false, false, false, 0), false)
                .add(wrapItemAsHolder(Items.BEETROOT), new FoodAttributes(10, 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()),0, 0, 0, 0.3, false, false, false, 0), false)
                .add(wrapItemAsHolder(Items.BEETROOT_SOUP), new FoodAttributes(10, 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 0, 0, 0.5, false, false, false, 0), false)
                .add(wrapItemAsHolder(Items.BREAD), new FoodAttributes(10, 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 0, 0, 0.4, false, false, false, 0), false)
                .add(wrapItemAsHolder(Items.CAKE), new FoodAttributes(10, 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 0, 0, 0.7, false, false, false, 0), false)
                .add(wrapItemAsHolder(Items.CARROT), new FoodAttributes(10, 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 0, 0, 0.3, false, false, false, 0), false)
                .add(wrapItemAsHolder(Items.CHICKEN), new FoodAttributes(10, 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 0, 0, 0.4, false, false, false, 0), false)
                .add(wrapItemAsHolder(Items.CHORUS_FRUIT), new FoodAttributes(10, 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()),0, 0, 0, 0.4, false, false, false, 0), false)
                .add(wrapItemAsHolder(Items.COD), new FoodAttributes(10, 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 0, 0, 0.5, false, false, false, 0), false)
                .add(wrapItemAsHolder(Items.COOKIE), new FoodAttributes(10, 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 0, 0, 0.15, false, false, false, 0), false)
                .add(wrapItemAsHolder(Items.COOKED_BEEF), new FoodAttributes(10, 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 0, 0, 0.6, false, false, false, 0), false)
                .add(wrapItemAsHolder(Items.COOKED_CHICKEN), new FoodAttributes(10, 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 0, 0, 0.5, false, false, false, 0), false)
                .add(wrapItemAsHolder(Items.COOKED_COD), new FoodAttributes(10, 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 0, 0, 0.4, false, false, false, 0), false)
                .add(wrapItemAsHolder(Items.COOKED_MUTTON), new FoodAttributes(10, 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 0, 0, 0.5, false, false, false, 0), false)
                .add(wrapItemAsHolder(Items.COOKED_PORKCHOP), new FoodAttributes(10, 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 0, 0, 0.6, false, false, false, 0), false)
                .add(wrapItemAsHolder(Items.COOKED_RABBIT), new FoodAttributes(10, 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 0, 0, 0.5, false, false, false, 0), false)
                .add(wrapItemAsHolder(Items.COOKED_SALMON), new FoodAttributes(10, 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 0, 0, 0.4, false, false, false, 0), false)
                .add(wrapItemAsHolder(Items.DRIED_KELP), new FoodAttributes(10, 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 0, 0, 0.1, false, false, false, 0), false)
                .add(wrapItemAsHolder(Items.ENCHANTED_GOLDEN_APPLE), new FoodAttributes(10, 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 0, 0, 3, false, false, false, 0), false)
                .add(wrapItemAsHolder(Items.GLOW_BERRIES), new FoodAttributes(10, 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 0, 0, 0.2, false, false, false, 0), false)
                .add(wrapItemAsHolder(Items.GOLDEN_APPLE), new FoodAttributes(10, 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 0, 0, 2, false, false, false, 0), false)
                .add(wrapItemAsHolder(Items.GOLDEN_CARROT), new FoodAttributes(10, 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 0, 0, 0.5, false, false, false, 0), false)
                .add(wrapItemAsHolder(Items.HONEY_BOTTLE), new FoodAttributes(10, 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 0, 0, 0.5, false, false, false, 0), false)
                .add(wrapItemAsHolder(Items.LINGERING_POTION), new FoodAttributes(10, 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 0, 0, 1, false, false, false, 0), false)
                .add(wrapItemAsHolder(Items.MELON_SLICE), new FoodAttributes(10, 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 0, 0, 0.25, false, false, false, 0), false)
                .add(wrapItemAsHolder(Items.MILK_BUCKET), new FoodAttributes(10, 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 0, 0, 1, false, false, false, 0), false)
                .add(wrapItemAsHolder(Items.MUSHROOM_STEW), new FoodAttributes(10, 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 0, 0, 0.5, false, false, false, 0), false)
                .add(wrapItemAsHolder(Items.MUTTON), new FoodAttributes(10, 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 0, 0, 0.5, false, false, false, 0), false)
                .add(wrapItemAsHolder(Items.POISONOUS_POTATO), new FoodAttributes(10, 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 0, 0, 0.2, false, false, false, 0), false)
                .add(wrapItemAsHolder(Items.PORKCHOP), new FoodAttributes(10, 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 0, 0, 0.6, false, false, false, 0), false)
                .add(wrapItemAsHolder(Items.POTATO), new FoodAttributes(10, 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 0, 0, 0.3, false, false, false, 0), false)
                .add(wrapItemAsHolder(Items.POTION), new FoodAttributes(10, 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 0, 0, 1, false, false, false, 0), false)
                .add(wrapItemAsHolder(Items.PUMPKIN_PIE), new FoodAttributes(10, 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 0, 0, 0.7, false, false, false, 0), false)
                .add(wrapItemAsHolder(Items.PUFFERFISH), new FoodAttributes(10, 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 0, 0, 0.5, false, false, false, 0), false)
                .add(wrapItemAsHolder(Items.RABBIT), new FoodAttributes(10, 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 0, 0, 0.5, false, false, false, 0), false)
                .add(wrapItemAsHolder(Items.RABBIT_STEW), new FoodAttributes(10, 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 0, 0, 0.6, false, false, false, 0), false)
                .add(wrapItemAsHolder(Items.ROTTEN_FLESH), new FoodAttributes(10, 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 0, 0, 0.5, false, false, false, 0), false)
                .add(wrapItemAsHolder(Items.SALMON), new FoodAttributes(10, 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 0, 0, 0.5, false, false, false, 0), false)
                .add(wrapItemAsHolder(Items.SPIDER_EYE), new FoodAttributes(10, 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 0, 0, 0.25, false, false, false, 0), false)
                .add(wrapItemAsHolder(Items.SPLASH_POTION), new FoodAttributes(10, 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 0, 0, 1, false, false, false, 0), false)
                .add(wrapItemAsHolder(Items.SUSPICIOUS_STEW), new FoodAttributes(10, 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 0, 0, 0.8, false, false, false, 0), false)
                .add(wrapItemAsHolder(Items.SWEET_BERRIES), new FoodAttributes(10, 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 0, 0, 0.2, false, false, false, 0), false)
                .add(wrapItemAsHolder(Items.TROPICAL_FISH), new FoodAttributes(10, 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 0, 0, 0.3, false, false, false, 0), false)
                .add(wrapItemAsHolder(Items.WHEAT), new FoodAttributes(10, 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, List.of(FalloutMcEffects.EXAMPLE_EFFECT.value()), 0, 0, 0, 0.25, false, false, false, 0), false);
    }
}
